//! CPython 3.13.9 VM instructions.

// This file is generated by scripts/update_instr.py
// Do not edit!

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum RealInstruction {
    BeforeAsyncWith = 1,
    BeforeWith = 2,
    BinaryOp(crate::Arg<crate::BinaryOperatorOparg>) = 45,
    BinaryOpAddFloat(crate::Arg<crate::BinaryOperatorOparg>) = 150,
    BinaryOpAddInt(crate::Arg<crate::BinaryOperatorOparg>) = 151,
    BinaryOpAddUnicode(crate::Arg<crate::BinaryOperatorOparg>) = 152,
    BinaryOpInplaceAddUnicode(crate::Arg<crate::BinaryOperatorOparg>) = 3,
    BinaryOpMultiplyFloat(crate::Arg<crate::BinaryOperatorOparg>) = 153,
    BinaryOpMultiplyInt(crate::Arg<crate::BinaryOperatorOparg>) = 154,
    BinaryOpSubtractFloat(crate::Arg<crate::BinaryOperatorOparg>) = 155,
    BinaryOpSubtractInt(crate::Arg<crate::BinaryOperatorOparg>) = 156,
    BinarySlice = 4,
    BinarySubscr = 5,
    BinarySubscrDict = 157,
    BinarySubscrGetitem = 158,
    BinarySubscrListInt = 159,
    BinarySubscrStrInt = 160,
    BinarySubscrTupleInt = 161,
    BuildConstKeyMap(crate::Arg<crate::Oparg>) = 46,
    BuildList(crate::Arg<crate::Oparg>) = 47,
    BuildMap(crate::Arg<crate::Oparg>) = 48,
    BuildSet(crate::Arg<crate::Oparg>) = 49,
    BuildSlice(crate::Arg<crate::Oparg>) = 50,
    BuildString(crate::Arg<crate::Oparg>) = 51,
    BuildTuple(crate::Arg<crate::Oparg>) = 52,
    Cache = 0,
    Call(crate::Arg<crate::Oparg>) = 53,
    CallAllocAndEnterInit(crate::Arg<crate::Oparg>) = 162,
    CallBoundMethodExactArgs(crate::Arg<crate::Oparg>) = 163,
    CallBoundMethodGeneral(crate::Arg<crate::Oparg>) = 164,
    CallBuiltinClass(crate::Arg<crate::Oparg>) = 165,
    CallBuiltinFast(crate::Arg<crate::Oparg>) = 166,
    CallBuiltinFastWithKeywords(crate::Arg<crate::Oparg>) = 167,
    CallBuiltinO(crate::Arg<crate::Oparg>) = 168,
    CallFunctionEx(crate::Arg<crate::Oparg>) = 54,
    CallIntrinsic1(crate::Arg<crate::CallIntrinsic1Oparg>) = 55,
    CallIntrinsic2(crate::Arg<crate::CallIntrinsic2Oparg>) = 56,
    CallIsinstance(crate::Arg<crate::Oparg>) = 169,
    CallKw(crate::Arg<crate::Oparg>) = 57,
    CallLen(crate::Arg<crate::Oparg>) = 170,
    CallListAppend(crate::Arg<crate::Oparg>) = 171,
    CallMethodDescriptorFast(crate::Arg<crate::Oparg>) = 172,
    CallMethodDescriptorFastWithKeywords(crate::Arg<crate::Oparg>) = 173,
    CallMethodDescriptorNoargs(crate::Arg<crate::Oparg>) = 174,
    CallMethodDescriptorO(crate::Arg<crate::Oparg>) = 175,
    CallNonPyGeneral(crate::Arg<crate::Oparg>) = 176,
    CallPyExactArgs(crate::Arg<crate::Oparg>) = 177,
    CallPyGeneral(crate::Arg<crate::Oparg>) = 178,
    CallStr1(crate::Arg<crate::Oparg>) = 179,
    CallTuple1(crate::Arg<crate::Oparg>) = 180,
    CallType1(crate::Arg<crate::Oparg>) = 181,
    CheckEgMatch = 6,
    CheckExcMatch = 7,
    CleanupThrow = 8,
    CompareOp(crate::Arg<crate::Oparg>) = 58,
    CompareOpFloat(crate::Arg<crate::Oparg>) = 182,
    CompareOpInt(crate::Arg<crate::Oparg>) = 183,
    CompareOpStr(crate::Arg<crate::Oparg>) = 184,
    ContainsOp(crate::Arg<crate::Oparg>) = 59,
    ContainsOpDict(crate::Arg<crate::Oparg>) = 185,
    ContainsOpSet(crate::Arg<crate::Oparg>) = 186,
    ConvertValue(crate::Arg<crate::Oparg>) = 60,
    Copy(crate::Arg<crate::Oparg>) = 61,
    CopyFreeVars(crate::Arg<crate::Oparg>) = 62,
    DeleteAttr(crate::Arg<crate::NameIdxOparg>) = 63,
    DeleteDeref(crate::Arg<crate::Oparg>) = 64,
    DeleteFast(crate::Arg<crate::Oparg>) = 65,
    DeleteGlobal(crate::Arg<crate::NameIdxOparg>) = 66,
    DeleteName(crate::Arg<crate::NameIdxOparg>) = 67,
    DeleteSubscr = 9,
    DictMerge(crate::Arg<crate::Oparg>) = 68,
    DictUpdate(crate::Arg<crate::Oparg>) = 69,
    EndAsyncFor = 10,
    EndFor = 11,
    EndSend = 12,
    EnterExecutor(crate::Arg<crate::Oparg>) = 70,
    ExitInitCheck = 13,
    ExtendedArg(crate::Arg<crate::Oparg>) = 71,
    FormatSimple = 14,
    FormatWithSpec = 15,
    ForIter(crate::Arg<crate::DeltaOparg>) = 72,
    ForIterGen(crate::Arg<crate::DeltaOparg>) = 187,
    ForIterList(crate::Arg<crate::DeltaOparg>) = 188,
    ForIterRange(crate::Arg<crate::DeltaOparg>) = 189,
    ForIterTuple(crate::Arg<crate::DeltaOparg>) = 190,
    GetAiter = 16,
    GetAnext = 18,
    GetAwaitable(crate::Arg<crate::Oparg>) = 73,
    GetIter = 19,
    GetLen = 20,
    GetYieldFromIter = 21,
    ImportFrom(crate::Arg<crate::NameIdxOparg>) = 74,
    ImportName(crate::Arg<crate::NameIdxOparg>) = 75,
    InstrumentedCall(crate::Arg<crate::Oparg>) = 244,
    InstrumentedCallFunctionEx = 246,
    InstrumentedCallKw(crate::Arg<crate::Oparg>) = 245,
    InstrumentedEndFor = 237,
    InstrumentedEndSend = 238,
    InstrumentedForIter(crate::Arg<crate::Oparg>) = 243,
    InstrumentedInstruction = 247,
    InstrumentedJumpBackward(crate::Arg<crate::Oparg>) = 249,
    InstrumentedJumpForward(crate::Arg<crate::Oparg>) = 248,
    InstrumentedLine = 254,
    InstrumentedLoadSuperAttr(crate::Arg<crate::Oparg>) = 242,
    InstrumentedPopJumpIfFalse(crate::Arg<crate::Oparg>) = 251,
    InstrumentedPopJumpIfNone(crate::Arg<crate::Oparg>) = 252,
    InstrumentedPopJumpIfNotNone(crate::Arg<crate::Oparg>) = 253,
    InstrumentedPopJumpIfTrue(crate::Arg<crate::Oparg>) = 250,
    InstrumentedResume(crate::Arg<crate::Oparg>) = 236,
    InstrumentedReturnConst(crate::Arg<crate::ConstIdxOparg>) = 240,
    InstrumentedReturnValue = 239,
    InstrumentedYieldValue(crate::Arg<crate::Oparg>) = 241,
    InterpreterExit = 22,
    IsOp(crate::Arg<crate::Oparg>) = 76,
    JumpBackward(crate::Arg<crate::DeltaOparg>) = 77,
    JumpBackwardNoInterrupt(crate::Arg<crate::DeltaOparg>) = 78,
    JumpForward(crate::Arg<crate::DeltaOparg>) = 79,
    ListAppend(crate::Arg<crate::Oparg>) = 80,
    ListExtend(crate::Arg<crate::Oparg>) = 81,
    LoadAssertionError = 23,
    LoadAttr(crate::Arg<crate::NameIdxOparg>) = 82,
    LoadAttrClass(crate::Arg<crate::NameIdxOparg>) = 191,
    LoadAttrGetattributeOverridden(crate::Arg<crate::NameIdxOparg>) = 192,
    LoadAttrInstanceValue(crate::Arg<crate::NameIdxOparg>) = 193,
    LoadAttrMethodLazyDict(crate::Arg<crate::NameIdxOparg>) = 194,
    LoadAttrMethodNoDict(crate::Arg<crate::NameIdxOparg>) = 195,
    LoadAttrMethodWithValues(crate::Arg<crate::NameIdxOparg>) = 196,
    LoadAttrModule(crate::Arg<crate::NameIdxOparg>) = 197,
    LoadAttrNondescriptorNoDict(crate::Arg<crate::NameIdxOparg>) = 198,
    LoadAttrNondescriptorWithValues(crate::Arg<crate::NameIdxOparg>) = 199,
    LoadAttrProperty(crate::Arg<crate::NameIdxOparg>) = 200,
    LoadAttrSlot(crate::Arg<crate::NameIdxOparg>) = 201,
    LoadAttrWithHint(crate::Arg<crate::NameIdxOparg>) = 202,
    LoadBuildClass = 24,
    LoadConst(crate::Arg<crate::ConstIdxOparg>) = 83,
    LoadDeref(crate::Arg<crate::Oparg>) = 84,
    LoadFast(crate::Arg<crate::Oparg>) = 85,
    LoadFastAndClear(crate::Arg<crate::Oparg>) = 86,
    LoadFastCheck(crate::Arg<crate::Oparg>) = 87,
    LoadFastLoadFast(crate::Arg<crate::Oparg>) = 88,
    LoadFromDictOrDeref(crate::Arg<crate::Oparg>) = 89,
    LoadFromDictOrGlobals(crate::Arg<crate::NameIdxOparg>) = 90,
    LoadGlobal(crate::Arg<crate::NameIdxOparg>) = 91,
    LoadGlobalBuiltin(crate::Arg<crate::NameIdxOparg>) = 203,
    LoadGlobalModule(crate::Arg<crate::NameIdxOparg>) = 204,
    LoadLocals = 25,
    LoadName(crate::Arg<crate::NameIdxOparg>) = 92,
    LoadSuperAttr(crate::Arg<crate::NameIdxOparg>) = 93,
    LoadSuperAttrAttr(crate::Arg<crate::NameIdxOparg>) = 205,
    LoadSuperAttrMethod(crate::Arg<crate::NameIdxOparg>) = 206,
    MakeCell(crate::Arg<crate::Oparg>) = 94,
    MakeFunction = 26,
    MapAdd(crate::Arg<crate::Oparg>) = 95,
    MatchClass(crate::Arg<crate::Oparg>) = 96,
    MatchKeys = 27,
    MatchMapping = 28,
    MatchSequence = 29,
    Nop = 30,
    PopExcept = 31,
    PopJumpIfFalse(crate::Arg<crate::DeltaOparg>) = 97,
    PopJumpIfNone(crate::Arg<crate::DeltaOparg>) = 98,
    PopJumpIfNotNone(crate::Arg<crate::DeltaOparg>) = 99,
    PopJumpIfTrue(crate::Arg<crate::DeltaOparg>) = 100,
    PopTop = 32,
    PushExcInfo = 33,
    PushNull = 34,
    RaiseVarargs(crate::Arg<crate::RaiseVarArgsOparg>) = 101,
    Reraise(crate::Arg<crate::Oparg>) = 102,
    Reserved = 17,
    Resume(crate::Arg<crate::ResumeOparg>) = 149,
    ResumeCheck(crate::Arg<crate::ResumeOparg>) = 207,
    ReturnConst(crate::Arg<crate::ConstIdxOparg>) = 103,
    ReturnGenerator = 35,
    ReturnValue = 36,
    Send(crate::Arg<crate::DeltaOparg>) = 104,
    SendGen(crate::Arg<crate::DeltaOparg>) = 208,
    SetupAnnotations = 37,
    SetAdd(crate::Arg<crate::Oparg>) = 105,
    SetFunctionAttribute(crate::Arg<crate::Oparg>) = 106,
    SetUpdate(crate::Arg<crate::Oparg>) = 107,
    StoreAttr(crate::Arg<crate::NameIdxOparg>) = 108,
    StoreAttrInstanceValue(crate::Arg<crate::NameIdxOparg>) = 209,
    StoreAttrSlot(crate::Arg<crate::NameIdxOparg>) = 210,
    StoreAttrWithHint(crate::Arg<crate::NameIdxOparg>) = 211,
    StoreDeref(crate::Arg<crate::Oparg>) = 109,
    StoreFast(crate::Arg<crate::Oparg>) = 110,
    StoreFastLoadFast(crate::Arg<crate::Oparg>) = 111,
    StoreFastStoreFast(crate::Arg<crate::Oparg>) = 112,
    StoreGlobal(crate::Arg<crate::NameIdxOparg>) = 113,
    StoreName(crate::Arg<crate::NameIdxOparg>) = 114,
    StoreSlice = 38,
    StoreSubscr = 39,
    StoreSubscrDict = 212,
    StoreSubscrListInt = 213,
    Swap(crate::Arg<crate::Oparg>) = 115,
    ToBool = 40,
    ToBoolAlwaysTrue = 214,
    ToBoolBool = 215,
    ToBoolInt = 216,
    ToBoolList = 217,
    ToBoolNone = 218,
    ToBoolStr = 219,
    UnaryInvert = 41,
    UnaryNegative = 42,
    UnaryNot = 43,
    UnpackEx(crate::Arg<crate::UnpackExOparg>) = 116,
    UnpackSequence(crate::Arg<crate::Oparg>) = 117,
    UnpackSequenceList(crate::Arg<crate::Oparg>) = 220,
    UnpackSequenceTuple(crate::Arg<crate::Oparg>) = 221,
    UnpackSequenceTwoTuple(crate::Arg<crate::Oparg>) = 222,
    WithExceptStart = 44,
    YieldValue(crate::Arg<crate::Oparg>) = 118,
}

impl RealInstruction {
    pub const fn deopt(self) -> Option<Self> {
        // Should we group these?
        Some(match self {
            Self::BinaryOpAddFloat(value) => Self::BinaryOp(value),
            Self::BinaryOpAddInt(value) => Self::BinaryOp(value),
            Self::BinaryOpAddUnicode(value) => Self::BinaryOp(value),
            Self::BinaryOpInplaceAddUnicode(value) => Self::BinaryOp(value),
            Self::BinaryOpMultiplyFloat(value) => Self::BinaryOp(value),
            Self::BinaryOpMultiplyInt(value) => Self::BinaryOp(value),
            Self::BinaryOpSubtractFloat(value) => Self::BinaryOp(value),
            Self::BinaryOpSubtractInt(value) => Self::BinaryOp(value),
            Self::BinarySubscrDict => Self::BinarySubscr,
            Self::BinarySubscrGetitem => Self::BinarySubscr,
            Self::BinarySubscrListInt => Self::BinarySubscr,
            Self::BinarySubscrStrInt => Self::BinarySubscr,
            Self::BinarySubscrTupleInt => Self::BinarySubscr,
            Self::CallAllocAndEnterInit(value) => Self::Call(value),
            Self::CallBoundMethodExactArgs(value) => Self::Call(value),
            Self::CallBoundMethodGeneral(value) => Self::Call(value),
            Self::CallBuiltinClass(value) => Self::Call(value),
            Self::CallBuiltinFast(value) => Self::Call(value),
            Self::CallBuiltinFastWithKeywords(value) => Self::Call(value),
            Self::CallBuiltinO(value) => Self::Call(value),
            Self::CallIsinstance(value) => Self::Call(value),
            Self::CallLen(value) => Self::Call(value),
            Self::CallListAppend(value) => Self::Call(value),
            Self::CallMethodDescriptorFast(value) => Self::Call(value),
            Self::CallMethodDescriptorFastWithKeywords(value) => Self::Call(value),
            Self::CallMethodDescriptorNoargs(value) => Self::Call(value),
            Self::CallMethodDescriptorO(value) => Self::Call(value),
            Self::CallNonPyGeneral(value) => Self::Call(value),
            Self::CallPyExactArgs(value) => Self::Call(value),
            Self::CallPyGeneral(value) => Self::Call(value),
            Self::CallStr1(value) => Self::Call(value),
            Self::CallTuple1(value) => Self::Call(value),
            Self::CallType1(value) => Self::Call(value),
            Self::CompareOpFloat(value) => Self::CompareOp(value),
            Self::CompareOpInt(value) => Self::CompareOp(value),
            Self::CompareOpStr(value) => Self::CompareOp(value),
            Self::ContainsOpDict(value) => Self::ContainsOp(value),
            Self::ContainsOpSet(value) => Self::ContainsOp(value),
            Self::ForIterGen(value) => Self::ForIter(value),
            Self::ForIterList(value) => Self::ForIter(value),
            Self::ForIterRange(value) => Self::ForIter(value),
            Self::ForIterTuple(value) => Self::ForIter(value),
            Self::LoadAttrClass(value) => Self::LoadAttr(value),
            Self::LoadAttrGetattributeOverridden(value) => Self::LoadAttr(value),
            Self::LoadAttrInstanceValue(value) => Self::LoadAttr(value),
            Self::LoadAttrMethodLazyDict(value) => Self::LoadAttr(value),
            Self::LoadAttrMethodNoDict(value) => Self::LoadAttr(value),
            Self::LoadAttrMethodWithValues(value) => Self::LoadAttr(value),
            Self::LoadAttrModule(value) => Self::LoadAttr(value),
            Self::LoadAttrNondescriptorNoDict(value) => Self::LoadAttr(value),
            Self::LoadAttrNondescriptorWithValues(value) => Self::LoadAttr(value),
            Self::LoadAttrProperty(value) => Self::LoadAttr(value),
            Self::LoadAttrSlot(value) => Self::LoadAttr(value),
            Self::LoadAttrWithHint(value) => Self::LoadAttr(value),
            Self::LoadGlobalBuiltin(value) => Self::LoadGlobal(value),
            Self::LoadGlobalModule(value) => Self::LoadGlobal(value),
            Self::LoadSuperAttrAttr(value) => Self::LoadSuperAttr(value),
            Self::LoadSuperAttrMethod(value) => Self::LoadSuperAttr(value),
            Self::ResumeCheck(value) => Self::Resume(value),
            Self::SendGen(value) => Self::Send(value),
            Self::StoreAttrInstanceValue(value) => Self::StoreAttr(value),
            Self::StoreAttrSlot(value) => Self::StoreAttr(value),
            Self::StoreAttrWithHint(value) => Self::StoreAttr(value),
            Self::StoreSubscrDict => Self::StoreSubscr,
            Self::StoreSubscrListInt => Self::StoreSubscr,
            Self::ToBoolAlwaysTrue => Self::ToBool,
            Self::ToBoolBool => Self::ToBool,
            Self::ToBoolInt => Self::ToBool,
            Self::ToBoolList => Self::ToBool,
            Self::ToBoolNone => Self::ToBool,
            Self::ToBoolStr => Self::ToBool,
            Self::UnpackSequenceList(value) => Self::UnpackSequence(value),
            Self::UnpackSequenceTuple(value) => Self::UnpackSequence(value),
            Self::UnpackSequenceTwoTuple(value) => Self::UnpackSequence(value),
            _ => return None,
        })
    }

    /// Whether opcode ID have 'HAS_ARG_FLAG' set.
    #[must_use]
    pub const fn has_arg(self) -> bool {
        matches!(
            self,
            Self::BinaryOp(_)
                | Self::BuildConstKeyMap(_)
                | Self::BuildList(_)
                | Self::BuildMap(_)
                | Self::BuildSet(_)
                | Self::BuildSlice(_)
                | Self::BuildString(_)
                | Self::BuildTuple(_)
                | Self::Call(_)
                | Self::CallAllocAndEnterInit(_)
                | Self::CallBoundMethodExactArgs(_)
                | Self::CallBoundMethodGeneral(_)
                | Self::CallBuiltinClass(_)
                | Self::CallBuiltinFast(_)
                | Self::CallBuiltinFastWithKeywords(_)
                | Self::CallBuiltinO(_)
                | Self::CallFunctionEx(_)
                | Self::CallIntrinsic1(_)
                | Self::CallIntrinsic2(_)
                | Self::CallIsinstance(_)
                | Self::CallKw(_)
                | Self::CallLen(_)
                | Self::CallListAppend(_)
                | Self::CallMethodDescriptorFast(_)
                | Self::CallMethodDescriptorFastWithKeywords(_)
                | Self::CallMethodDescriptorNoargs(_)
                | Self::CallMethodDescriptorO(_)
                | Self::CallNonPyGeneral(_)
                | Self::CallPyExactArgs(_)
                | Self::CallPyGeneral(_)
                | Self::CallStr1(_)
                | Self::CallTuple1(_)
                | Self::CallType1(_)
                | Self::CompareOp(_)
                | Self::CompareOpFloat(_)
                | Self::CompareOpInt(_)
                | Self::CompareOpStr(_)
                | Self::ContainsOp(_)
                | Self::ContainsOpDict(_)
                | Self::ContainsOpSet(_)
                | Self::ConvertValue(_)
                | Self::Copy(_)
                | Self::CopyFreeVars(_)
                | Self::DeleteAttr(_)
                | Self::DeleteDeref(_)
                | Self::DeleteFast(_)
                | Self::DeleteGlobal(_)
                | Self::DeleteName(_)
                | Self::DictMerge(_)
                | Self::DictUpdate(_)
                | Self::EnterExecutor(_)
                | Self::ExtendedArg(_)
                | Self::ForIter(_)
                | Self::ForIterGen(_)
                | Self::ForIterList(_)
                | Self::ForIterRange(_)
                | Self::ForIterTuple(_)
                | Self::GetAwaitable(_)
                | Self::ImportFrom(_)
                | Self::ImportName(_)
                | Self::InstrumentedCall(_)
                | Self::InstrumentedCallKw(_)
                | Self::InstrumentedForIter(_)
                | Self::InstrumentedJumpBackward(_)
                | Self::InstrumentedJumpForward(_)
                | Self::InstrumentedLoadSuperAttr(_)
                | Self::InstrumentedPopJumpIfFalse(_)
                | Self::InstrumentedPopJumpIfNone(_)
                | Self::InstrumentedPopJumpIfNotNone(_)
                | Self::InstrumentedPopJumpIfTrue(_)
                | Self::InstrumentedResume(_)
                | Self::InstrumentedReturnConst(_)
                | Self::InstrumentedYieldValue(_)
                | Self::IsOp(_)
                | Self::JumpBackward(_)
                | Self::JumpBackwardNoInterrupt(_)
                | Self::JumpForward(_)
                | Self::ListAppend(_)
                | Self::ListExtend(_)
                | Self::LoadAttr(_)
                | Self::LoadAttrClass(_)
                | Self::LoadAttrGetattributeOverridden(_)
                | Self::LoadAttrInstanceValue(_)
                | Self::LoadAttrMethodLazyDict(_)
                | Self::LoadAttrMethodNoDict(_)
                | Self::LoadAttrMethodWithValues(_)
                | Self::LoadAttrModule(_)
                | Self::LoadAttrNondescriptorNoDict(_)
                | Self::LoadAttrNondescriptorWithValues(_)
                | Self::LoadAttrProperty(_)
                | Self::LoadAttrSlot(_)
                | Self::LoadAttrWithHint(_)
                | Self::LoadConst(_)
                | Self::LoadDeref(_)
                | Self::LoadFast(_)
                | Self::LoadFastAndClear(_)
                | Self::LoadFastCheck(_)
                | Self::LoadFastLoadFast(_)
                | Self::LoadFromDictOrDeref(_)
                | Self::LoadFromDictOrGlobals(_)
                | Self::LoadGlobal(_)
                | Self::LoadGlobalBuiltin(_)
                | Self::LoadGlobalModule(_)
                | Self::LoadName(_)
                | Self::LoadSuperAttr(_)
                | Self::LoadSuperAttrAttr(_)
                | Self::LoadSuperAttrMethod(_)
                | Self::MakeCell(_)
                | Self::MapAdd(_)
                | Self::MatchClass(_)
                | Self::PopJumpIfFalse(_)
                | Self::PopJumpIfNone(_)
                | Self::PopJumpIfNotNone(_)
                | Self::PopJumpIfTrue(_)
                | Self::RaiseVarargs(_)
                | Self::Reraise(_)
                | Self::Resume(_)
                | Self::ReturnConst(_)
                | Self::Send(_)
                | Self::SendGen(_)
                | Self::SetAdd(_)
                | Self::SetFunctionAttribute(_)
                | Self::SetUpdate(_)
                | Self::StoreAttr(_)
                | Self::StoreAttrWithHint(_)
                | Self::StoreDeref(_)
                | Self::StoreFast(_)
                | Self::StoreFastLoadFast(_)
                | Self::StoreFastStoreFast(_)
                | Self::StoreGlobal(_)
                | Self::StoreName(_)
                | Self::Swap(_)
                | Self::UnpackEx(_)
                | Self::UnpackSequence(_)
                | Self::UnpackSequenceList(_)
                | Self::UnpackSequenceTuple(_)
                | Self::UnpackSequenceTwoTuple(_)
                | Self::YieldValue(_)
        )
    }

    /// Whether opcode ID have 'HAS_CONST_FLAG' set.
    #[must_use]
    pub const fn has_const(self) -> bool {
        matches!(
            self,
            Self::InstrumentedReturnConst(_) | Self::LoadConst(_) | Self::ReturnConst(_)
        )
    }

    /// Whether opcode ID have 'HAS_PURE_FLAG' set.
    #[must_use]
    pub const fn has_exc(self) -> bool {
        matches!(
            self,
            Self::Copy(_)
                | Self::EndFor
                | Self::EndSend
                | Self::InstrumentedLine
                | Self::LoadConst(_)
                | Self::LoadFast(_)
                | Self::Nop
                | Self::PopTop
                | Self::PushNull
                | Self::Swap(_)
                | Self::UnaryNot
        )
    }

    /// Whether opcode ID have 'HAS_FREE_FLAG' set.
    #[must_use]
    pub const fn has_free(self) -> bool {
        matches!(
            self,
            Self::DeleteDeref(_)
                | Self::LoadDeref(_)
                | Self::LoadFromDictOrDeref(_)
                | Self::MakeCell(_)
                | Self::StoreDeref(_)
        )
    }

    /// Whether opcode ID have 'HAS_JUMP_FLAG' set.
    #[must_use]
    pub const fn has_jump(self) -> bool {
        matches!(
            self,
            Self::ForIter(_)
                | Self::ForIterList(_)
                | Self::ForIterRange(_)
                | Self::ForIterTuple(_)
                | Self::JumpBackward(_)
                | Self::JumpBackwardNoInterrupt(_)
                | Self::JumpForward(_)
                | Self::PopJumpIfFalse(_)
                | Self::PopJumpIfNone(_)
                | Self::PopJumpIfNotNone(_)
                | Self::PopJumpIfTrue(_)
                | Self::Send(_)
        )
    }

    /// Whether opcode ID have 'HAS_LOCAL_FLAG' set.
    #[must_use]
    pub const fn has_local(self) -> bool {
        matches!(
            self,
            Self::BinaryOpInplaceAddUnicode(_)
                | Self::DeleteFast(_)
                | Self::LoadFast(_)
                | Self::LoadFastAndClear(_)
                | Self::LoadFastCheck(_)
                | Self::LoadFastLoadFast(_)
                | Self::StoreFast(_)
                | Self::StoreFastLoadFast(_)
                | Self::StoreFastStoreFast(_)
        )
    }

    /// Whether opcode ID have 'HAS_NAME_FLAG' set.
    #[must_use]
    pub const fn has_name(self) -> bool {
        matches!(
            self,
            Self::DeleteAttr(_)
                | Self::DeleteGlobal(_)
                | Self::DeleteName(_)
                | Self::ImportFrom(_)
                | Self::ImportName(_)
                | Self::LoadAttr(_)
                | Self::LoadAttrGetattributeOverridden(_)
                | Self::LoadAttrWithHint(_)
                | Self::LoadFromDictOrGlobals(_)
                | Self::LoadGlobal(_)
                | Self::LoadName(_)
                | Self::LoadSuperAttr(_)
                | Self::LoadSuperAttrAttr(_)
                | Self::LoadSuperAttrMethod(_)
                | Self::StoreAttr(_)
                | Self::StoreAttrWithHint(_)
                | Self::StoreGlobal(_)
                | Self::StoreName(_)
        )
    }

    /// How many items should be popped from the stack.
    pub const fn num_popped<T: crate::OpArgType>(self, oparg: T) -> u32 {
        match self {
            Self::BeforeAsyncWith => 1,
            Self::BeforeWith => 1,
            Self::BinaryOp => 2,
            Self::BinaryOpAddFloat => 2,
            Self::BinaryOpAddInt => 2,
            Self::BinaryOpAddUnicode => 2,
            Self::BinaryOpInplaceAddUnicode => 2,
            Self::BinaryOpMultiplyFloat => 2,
            Self::BinaryOpMultiplyInt => 2,
            Self::BinaryOpSubtractFloat => 2,
            Self::BinaryOpSubtractInt => 2,
            Self::BinarySlice => 3,
            Self::BinarySubscr => 2,
            Self::BinarySubscrDict => 2,
            Self::BinarySubscrGetitem => 2,
            Self::BinarySubscrListInt => 2,
            Self::BinarySubscrStrInt => 2,
            Self::BinarySubscrTupleInt => 2,
            Self::BuildConstKeyMap => 1 + oparg,
            Self::BuildList => oparg,
            Self::BuildMap => oparg * 2,
            Self::BuildSet => oparg,
            Self::BuildSlice => 2 + (if oparg == 3 { 1 } else { 0 }),
            Self::BuildString => oparg,
            Self::BuildTuple => oparg,
            Self::Cache => 0,
            Self::Call => 2 + oparg,
            Self::CallAllocAndEnterInit => 2 + oparg,
            Self::CallBoundMethodExactArgs => 2 + oparg,
            Self::CallBoundMethodGeneral => 2 + oparg,
            Self::CallBuiltinClass => 2 + oparg,
            Self::CallBuiltinFast => 2 + oparg,
            Self::CallBuiltinFastWithKeywords => 2 + oparg,
            Self::CallBuiltinO => 2 + oparg,
            Self::CallFunctionEx => 3 + (oparg & 1),
            Self::CallIntrinsic1 => 1,
            Self::CallIntrinsic2 => 2,
            Self::CallIsinstance => 2 + oparg,
            Self::CallKw => 3 + oparg,
            Self::CallLen => 2 + oparg,
            Self::CallListAppend => 3,
            Self::CallMethodDescriptorFast => 2 + oparg,
            Self::CallMethodDescriptorFastWithKeywords => 2 + oparg,
            Self::CallMethodDescriptorNoargs => 2 + oparg,
            Self::CallMethodDescriptorO => 2 + oparg,
            Self::CallNonPyGeneral => 2 + oparg,
            Self::CallPyExactArgs => 2 + oparg,
            Self::CallPyGeneral => 2 + oparg,
            Self::CallStr1 => 3,
            Self::CallTuple1 => 3,
            Self::CallType1 => 3,
            Self::CheckEgMatch => 2,
            Self::CheckExcMatch => 2,
            Self::CleanupThrow => 3,
            Self::CompareOp => 2,
            Self::CompareOpFloat => 2,
            Self::CompareOpInt => 2,
            Self::CompareOpStr => 2,
            Self::ContainsOp => 2,
            Self::ContainsOpDict => 2,
            Self::ContainsOpSet => 2,
            Self::ConvertValue => 1,
            Self::Copy => 1 + (oparg - 1),
            Self::CopyFreeVars => 0,
            Self::DeleteAttr => 1,
            Self::DeleteDeref => 0,
            Self::DeleteFast => 0,
            Self::DeleteGlobal => 0,
            Self::DeleteName => 0,
            Self::DeleteSubscr => 2,
            Self::DictMerge => 5 + (oparg - 1),
            Self::DictUpdate => 2 + (oparg - 1),
            Self::EndAsyncFor => 2,
            Self::EndFor => 1,
            Self::EndSend => 2,
            Self::EnterExecutor => 0,
            Self::ExitInitCheck => 1,
            Self::ExtendedArg => 0,
            Self::FormatSimple => 1,
            Self::FormatWithSpec => 2,
            Self::ForIter => 1,
            Self::ForIterGen => 1,
            Self::ForIterList => 1,
            Self::ForIterRange => 1,
            Self::ForIterTuple => 1,
            Self::GetAiter => 1,
            Self::GetAnext => 1,
            Self::GetAwaitable => 1,
            Self::GetIter => 1,
            Self::GetLen => 1,
            Self::GetYieldFromIter => 1,
            Self::ImportFrom => 1,
            Self::ImportName => 2,
            Self::InstrumentedCall => 0,
            Self::InstrumentedCallFunctionEx => 0,
            Self::InstrumentedCallKw => 0,
            Self::InstrumentedEndFor => 2,
            Self::InstrumentedEndSend => 2,
            Self::InstrumentedForIter => 0,
            Self::InstrumentedInstruction => 0,
            Self::InstrumentedJumpBackward => 0,
            Self::InstrumentedJumpForward => 0,
            Self::InstrumentedLine => 0,
            Self::InstrumentedLoadSuperAttr => 3,
            Self::InstrumentedPopJumpIfFalse => 0,
            Self::InstrumentedPopJumpIfNone => 0,
            Self::InstrumentedPopJumpIfNotNone => 0,
            Self::InstrumentedPopJumpIfTrue => 0,
            Self::InstrumentedResume => 0,
            Self::InstrumentedReturnConst => 0,
            Self::InstrumentedReturnValue => 1,
            Self::InstrumentedYieldValue => 1,
            Self::InterpreterExit => 1,
            Self::IsOp => 2,
            Self::JumpBackward => 0,
            Self::JumpBackwardNoInterrupt => 0,
            Self::JumpForward => 0,
            Self::ListAppend => 2 + (oparg - 1),
            Self::ListExtend => 2 + (oparg - 1),
            Self::LoadAssertionError => 0,
            Self::LoadAttr => 1,
            Self::LoadAttrClass => 1,
            Self::LoadAttrGetattributeOverridden => 1,
            Self::LoadAttrInstanceValue => 1,
            Self::LoadAttrMethodLazyDict => 1,
            Self::LoadAttrMethodNoDict => 1,
            Self::LoadAttrMethodWithValues => 1,
            Self::LoadAttrModule => 1,
            Self::LoadAttrNondescriptorNoDict => 1,
            Self::LoadAttrNondescriptorWithValues => 1,
            Self::LoadAttrProperty => 1,
            Self::LoadAttrSlot => 1,
            Self::LoadAttrWithHint => 1,
            Self::LoadBuildClass => 0,
            Self::LoadConst => 0,
            Self::LoadDeref => 0,
            Self::LoadFast => 0,
            Self::LoadFastAndClear => 0,
            Self::LoadFastCheck => 0,
            Self::LoadFastLoadFast => 0,
            Self::LoadFromDictOrDeref => 1,
            Self::LoadFromDictOrGlobals => 1,
            Self::LoadGlobal => 0,
            Self::LoadGlobalBuiltin => 0,
            Self::LoadGlobalModule => 0,
            Self::LoadLocals => 0,
            Self::LoadName => 0,
            Self::LoadSuperAttr => 3,
            Self::LoadSuperAttrAttr => 3,
            Self::LoadSuperAttrMethod => 3,
            Self::MakeCell => 0,
            Self::MakeFunction => 1,
            Self::MapAdd => 3 + (oparg - 1),
            Self::MatchClass => 3,
            Self::MatchKeys => 2,
            Self::MatchMapping => 1,
            Self::MatchSequence => 1,
            Self::Nop => 0,
            Self::PopExcept => 1,
            Self::PopJumpIfFalse => 1,
            Self::PopJumpIfNone => 1,
            Self::PopJumpIfNotNone => 1,
            Self::PopJumpIfTrue => 1,
            Self::PopTop => 1,
            Self::PushExcInfo => 1,
            Self::PushNull => 0,
            Self::RaiseVarargs => oparg,
            Self::Reraise => 1 + oparg,
            Self::Reserved => 0,
            Self::Resume => 0,
            Self::ResumeCheck => 0,
            Self::ReturnConst => 0,
            Self::ReturnGenerator => 0,
            Self::ReturnValue => 1,
            Self::Send => 2,
            Self::SendGen => 2,
            Self::SetupAnnotations => 0,
            Self::SetAdd => 2 + (oparg - 1),
            Self::SetFunctionAttribute => 2,
            Self::SetUpdate => 2 + (oparg - 1),
            Self::StoreAttr => 2,
            Self::StoreAttrInstanceValue => 2,
            Self::StoreAttrSlot => 2,
            Self::StoreAttrWithHint => 2,
            Self::StoreDeref => 1,
            Self::StoreFast => 1,
            Self::StoreFastLoadFast => 1,
            Self::StoreFastStoreFast => 2,
            Self::StoreGlobal => 1,
            Self::StoreName => 1,
            Self::StoreSlice => 4,
            Self::StoreSubscr => 3,
            Self::StoreSubscrDict => 3,
            Self::StoreSubscrListInt => 3,
            Self::Swap => 2 + (oparg - 2),
            Self::ToBool => 1,
            Self::ToBoolAlwaysTrue => 1,
            Self::ToBoolBool => 1,
            Self::ToBoolInt => 1,
            Self::ToBoolList => 1,
            Self::ToBoolNone => 1,
            Self::ToBoolStr => 1,
            Self::UnaryInvert => 1,
            Self::UnaryNegative => 1,
            Self::UnaryNot => 1,
            Self::UnpackEx => 1,
            Self::UnpackSequence => 1,
            Self::UnpackSequenceList => 1,
            Self::UnpackSequenceTuple => 1,
            Self::UnpackSequenceTwoTuple => 1,
            Self::WithExceptStart => 4,
            Self::YieldValue => 1,
        }
    }

    /// How many items should be pushed on the stack.
    pub const fn num_pushed<T: crate::OpArgType>(self, oparg: T) -> u32 {
        match self {
            Self::BeforeAsyncWith => 2,
            Self::BeforeWith => 2,
            Self::BinaryOp => 1,
            Self::BinaryOpAddFloat => 1,
            Self::BinaryOpAddInt => 1,
            Self::BinaryOpAddUnicode => 1,
            Self::BinaryOpInplaceAddUnicode => 0,
            Self::BinaryOpMultiplyFloat => 1,
            Self::BinaryOpMultiplyInt => 1,
            Self::BinaryOpSubtractFloat => 1,
            Self::BinaryOpSubtractInt => 1,
            Self::BinarySlice => 1,
            Self::BinarySubscr => 1,
            Self::BinarySubscrDict => 1,
            Self::BinarySubscrGetitem => 1,
            Self::BinarySubscrListInt => 1,
            Self::BinarySubscrStrInt => 1,
            Self::BinarySubscrTupleInt => 1,
            Self::BuildConstKeyMap => 1,
            Self::BuildList => 1,
            Self::BuildMap => 1,
            Self::BuildSet => 1,
            Self::BuildSlice => 1,
            Self::BuildString => 1,
            Self::BuildTuple => 1,
            Self::Cache => 0,
            Self::Call => 1,
            Self::CallAllocAndEnterInit => 1,
            Self::CallBoundMethodExactArgs => 0,
            Self::CallBoundMethodGeneral => 0,
            Self::CallBuiltinClass => 1,
            Self::CallBuiltinFast => 1,
            Self::CallBuiltinFastWithKeywords => 1,
            Self::CallBuiltinO => 1,
            Self::CallFunctionEx => 1,
            Self::CallIntrinsic1 => 1,
            Self::CallIntrinsic2 => 1,
            Self::CallIsinstance => 1,
            Self::CallKw => 1,
            Self::CallLen => 1,
            Self::CallListAppend => 1,
            Self::CallMethodDescriptorFast => 1,
            Self::CallMethodDescriptorFastWithKeywords => 1,
            Self::CallMethodDescriptorNoargs => 1,
            Self::CallMethodDescriptorO => 1,
            Self::CallNonPyGeneral => 1,
            Self::CallPyExactArgs => 0,
            Self::CallPyGeneral => 0,
            Self::CallStr1 => 1,
            Self::CallTuple1 => 1,
            Self::CallType1 => 1,
            Self::CheckEgMatch => 2,
            Self::CheckExcMatch => 2,
            Self::CleanupThrow => 2,
            Self::CompareOp => 1,
            Self::CompareOpFloat => 1,
            Self::CompareOpInt => 1,
            Self::CompareOpStr => 1,
            Self::ContainsOp => 1,
            Self::ContainsOpDict => 1,
            Self::ContainsOpSet => 1,
            Self::ConvertValue => 1,
            Self::Copy => 2 + (oparg - 1),
            Self::CopyFreeVars => 0,
            Self::DeleteAttr => 0,
            Self::DeleteDeref => 0,
            Self::DeleteFast => 0,
            Self::DeleteGlobal => 0,
            Self::DeleteName => 0,
            Self::DeleteSubscr => 0,
            Self::DictMerge => 4 + (oparg - 1),
            Self::DictUpdate => 1 + (oparg - 1),
            Self::EndAsyncFor => 0,
            Self::EndFor => 0,
            Self::EndSend => 1,
            Self::EnterExecutor => 0,
            Self::ExitInitCheck => 0,
            Self::ExtendedArg => 0,
            Self::FormatSimple => 1,
            Self::FormatWithSpec => 1,
            Self::ForIter => 2,
            Self::ForIterGen => 1,
            Self::ForIterList => 2,
            Self::ForIterRange => 2,
            Self::ForIterTuple => 2,
            Self::GetAiter => 1,
            Self::GetAnext => 2,
            Self::GetAwaitable => 1,
            Self::GetIter => 1,
            Self::GetLen => 2,
            Self::GetYieldFromIter => 1,
            Self::ImportFrom => 2,
            Self::ImportName => 1,
            Self::InstrumentedCall => 0,
            Self::InstrumentedCallFunctionEx => 0,
            Self::InstrumentedCallKw => 0,
            Self::InstrumentedEndFor => 1,
            Self::InstrumentedEndSend => 1,
            Self::InstrumentedForIter => 0,
            Self::InstrumentedInstruction => 0,
            Self::InstrumentedJumpBackward => 0,
            Self::InstrumentedJumpForward => 0,
            Self::InstrumentedLine => 0,
            Self::InstrumentedLoadSuperAttr => 1 + (oparg & 1),
            Self::InstrumentedPopJumpIfFalse => 0,
            Self::InstrumentedPopJumpIfNone => 0,
            Self::InstrumentedPopJumpIfNotNone => 0,
            Self::InstrumentedPopJumpIfTrue => 0,
            Self::InstrumentedResume => 0,
            Self::InstrumentedReturnConst => 0,
            Self::InstrumentedReturnValue => 0,
            Self::InstrumentedYieldValue => 1,
            Self::InterpreterExit => 0,
            Self::IsOp => 1,
            Self::JumpBackward => 0,
            Self::JumpBackwardNoInterrupt => 0,
            Self::JumpForward => 0,
            Self::ListAppend => 1 + (oparg - 1),
            Self::ListExtend => 1 + (oparg - 1),
            Self::LoadAssertionError => 1,
            Self::LoadAttr => 1 + (oparg & 1),
            Self::LoadAttrClass => 1 + (oparg & 1),
            Self::LoadAttrGetattributeOverridden => 1,
            Self::LoadAttrInstanceValue => 1 + (oparg & 1),
            Self::LoadAttrMethodLazyDict => 2,
            Self::LoadAttrMethodNoDict => 2,
            Self::LoadAttrMethodWithValues => 2,
            Self::LoadAttrModule => 1 + (oparg & 1),
            Self::LoadAttrNondescriptorNoDict => 1,
            Self::LoadAttrNondescriptorWithValues => 1,
            Self::LoadAttrProperty => 1,
            Self::LoadAttrSlot => 1 + (oparg & 1),
            Self::LoadAttrWithHint => 1 + (oparg & 1),
            Self::LoadBuildClass => 1,
            Self::LoadConst => 1,
            Self::LoadDeref => 1,
            Self::LoadFast => 1,
            Self::LoadFastAndClear => 1,
            Self::LoadFastCheck => 1,
            Self::LoadFastLoadFast => 2,
            Self::LoadFromDictOrDeref => 1,
            Self::LoadFromDictOrGlobals => 1,
            Self::LoadGlobal => 1 + (oparg & 1),
            Self::LoadGlobalBuiltin => 1 + (oparg & 1),
            Self::LoadGlobalModule => 1 + (oparg & 1),
            Self::LoadLocals => 1,
            Self::LoadName => 1,
            Self::LoadSuperAttr => 1 + (oparg & 1),
            Self::LoadSuperAttrAttr => 1,
            Self::LoadSuperAttrMethod => 2,
            Self::MakeCell => 0,
            Self::MakeFunction => 1,
            Self::MapAdd => 1 + (oparg - 1),
            Self::MatchClass => 1,
            Self::MatchKeys => 3,
            Self::MatchMapping => 2,
            Self::MatchSequence => 2,
            Self::Nop => 0,
            Self::PopExcept => 0,
            Self::PopJumpIfFalse => 0,
            Self::PopJumpIfNone => 0,
            Self::PopJumpIfNotNone => 0,
            Self::PopJumpIfTrue => 0,
            Self::PopTop => 0,
            Self::PushExcInfo => 2,
            Self::PushNull => 1,
            Self::RaiseVarargs => 0,
            Self::Reraise => oparg,
            Self::Reserved => 0,
            Self::Resume => 0,
            Self::ResumeCheck => 0,
            Self::ReturnConst => 0,
            Self::ReturnGenerator => 1,
            Self::ReturnValue => 0,
            Self::Send => 2,
            Self::SendGen => 2,
            Self::SetupAnnotations => 0,
            Self::SetAdd => 1 + (oparg - 1),
            Self::SetFunctionAttribute => 1,
            Self::SetUpdate => 1 + (oparg - 1),
            Self::StoreAttr => 0,
            Self::StoreAttrInstanceValue => 0,
            Self::StoreAttrSlot => 0,
            Self::StoreAttrWithHint => 0,
            Self::StoreDeref => 0,
            Self::StoreFast => 0,
            Self::StoreFastLoadFast => 1,
            Self::StoreFastStoreFast => 0,
            Self::StoreGlobal => 0,
            Self::StoreName => 0,
            Self::StoreSlice => 0,
            Self::StoreSubscr => 0,
            Self::StoreSubscrDict => 0,
            Self::StoreSubscrListInt => 0,
            Self::Swap => 2 + (oparg - 2),
            Self::ToBool => 1,
            Self::ToBoolAlwaysTrue => 1,
            Self::ToBoolBool => 1,
            Self::ToBoolInt => 1,
            Self::ToBoolList => 1,
            Self::ToBoolNone => 1,
            Self::ToBoolStr => 1,
            Self::UnaryInvert => 1,
            Self::UnaryNegative => 1,
            Self::UnaryNot => 1,
            Self::UnpackEx => 1 + (oparg >> 8) + (oparg & 0xFF),
            Self::UnpackSequence => oparg,
            Self::UnpackSequenceList => oparg,
            Self::UnpackSequenceTuple => oparg,
            Self::UnpackSequenceTwoTuple => 2,
            Self::WithExceptStart => 5,
            Self::YieldValue => 1,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum PseudoInstruction {
    Jump(crate::Arg<crate::DeltaOparg>) = 256,
    JumpNoInterrupt(crate::Arg<crate::DeltaOparg>) = 257,
    LoadClosure(crate::Arg<crate::Oparg>) = 258,
    LoadMethod(crate::Arg<crate::NameIdxOparg>) = 259,
    LoadSuperMethod(crate::Arg<crate::NameIdxOparg>) = 260,
    LoadZeroSuperAttr(crate::Arg<crate::NameIdxOparg>) = 261,
    LoadZeroSuperMethod(crate::Arg<crate::NameIdxOparg>) = 262,
    PopBlock = 263,
    SetupCleanup = 264,
    SetupFinally = 265,
    SetupWith = 266,
    StoreFastMaybeNull(crate::Arg<crate::Oparg>) = 267,
}

impl PseudoInstruction {
    /// Whether opcode ID have 'HAS_ARG_FLAG' set.
    #[must_use]
    pub const fn has_arg(self) -> bool {
        matches!(
            self,
            Self::Jump(_)
                | Self::JumpNoInterrupt(_)
                | Self::LoadClosure(_)
                | Self::LoadMethod(_)
                | Self::LoadSuperMethod(_)
                | Self::LoadZeroSuperAttr(_)
                | Self::LoadZeroSuperMethod(_)
                | Self::StoreFastMaybeNull(_)
        )
    }

    /// Whether opcode ID have 'HAS_CONST_FLAG' set.
    #[must_use]
    pub const fn has_const(self) -> bool {
        false
    }

    /// Whether opcode ID have 'HAS_PURE_FLAG' set.
    #[must_use]
    pub const fn has_exc(self) -> bool {
        matches!(
            self,
            Self::LoadClosure(_)
                | Self::PopBlock
                | Self::SetupCleanup
                | Self::SetupFinally
                | Self::SetupWith
        )
    }

    /// Whether opcode ID have 'HAS_FREE_FLAG' set.
    #[must_use]
    pub const fn has_free(self) -> bool {
        false
    }

    /// Whether opcode ID have 'HAS_JUMP_FLAG' set.
    #[must_use]
    pub const fn has_jump(self) -> bool {
        matches!(self, Self::Jump(_) | Self::JumpNoInterrupt(_))
    }

    /// Whether opcode ID have 'HAS_LOCAL_FLAG' set.
    #[must_use]
    pub const fn has_local(self) -> bool {
        matches!(self, Self::LoadClosure(_) | Self::StoreFastMaybeNull(_))
    }

    /// Whether opcode ID have 'HAS_NAME_FLAG' set.
    #[must_use]
    pub const fn has_name(self) -> bool {
        matches!(
            self,
            Self::LoadMethod(_)
                | Self::LoadSuperMethod(_)
                | Self::LoadZeroSuperAttr(_)
                | Self::LoadZeroSuperMethod(_)
        )
    }
}

const _: () = assert!(std::mem::size_of::<RealInstruction>() == 1);
const _: () = assert!(std::mem::size_of::<PseudoInstruction>() == 2);
