//! CPython 3.13.9 VM instructions.

// This file is generated by generate.py
// Do not edit!

use crate::{Oparg, OpargType};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum RealInstruction {
    BeforeAsyncWith = 1,
    BeforeWith = 2,
    BinaryOp(OpargType<crate::BinaryOperatorOparg>) = 45,
    BinaryOpAddFloat(OpargType<crate::BinaryOperatorOparg>) = 150,
    BinaryOpAddInt(OpargType<crate::BinaryOperatorOparg>) = 151,
    BinaryOpAddUnicode(OpargType<crate::BinaryOperatorOparg>) = 152,
    BinaryOpInplaceAddUnicode(OpargType<crate::BinaryOperatorOparg>) = 3,
    BinaryOpMultiplyFloat(OpargType<crate::BinaryOperatorOparg>) = 153,
    BinaryOpMultiplyInt(OpargType<crate::BinaryOperatorOparg>) = 154,
    BinaryOpSubtractFloat(OpargType<crate::BinaryOperatorOparg>) = 155,
    BinaryOpSubtractInt(OpargType<crate::BinaryOperatorOparg>) = 156,
    BinarySlice = 4,
    BinarySubscr = 5,
    BinarySubscrDict = 157,
    BinarySubscrGetitem = 158,
    BinarySubscrListInt = 159,
    BinarySubscrStrInt = 160,
    BinarySubscrTupleInt = 161,
    BuildConstKeyMap(OpargType<crate::Oparg>) = 46,
    BuildList(OpargType<crate::Oparg>) = 47,
    BuildMap(OpargType<crate::Oparg>) = 48,
    BuildSet(OpargType<crate::Oparg>) = 49,
    BuildSlice(OpargType<crate::Oparg>) = 50,
    BuildString(OpargType<crate::Oparg>) = 51,
    BuildTuple(OpargType<crate::Oparg>) = 52,
    Cache = 0,
    Call(OpargType<crate::Oparg>) = 53,
    CallAllocAndEnterInit(OpargType<crate::Oparg>) = 162,
    CallBoundMethodExactArgs(OpargType<crate::Oparg>) = 163,
    CallBoundMethodGeneral(OpargType<crate::Oparg>) = 164,
    CallBuiltinClass(OpargType<crate::Oparg>) = 165,
    CallBuiltinFast(OpargType<crate::Oparg>) = 166,
    CallBuiltinFastWithKeywords(OpargType<crate::Oparg>) = 167,
    CallBuiltinO(OpargType<crate::Oparg>) = 168,
    CallFunctionEx(OpargType<crate::Oparg>) = 54,
    CallIntrinsic1(OpargType<crate::CallIntrinsic1Oparg>) = 55,
    CallIntrinsic2(OpargType<crate::CallIntrinsic2Oparg>) = 56,
    CallIsinstance(OpargType<crate::Oparg>) = 169,
    CallKw(OpargType<crate::Oparg>) = 57,
    CallLen(OpargType<crate::Oparg>) = 170,
    CallListAppend(OpargType<crate::Oparg>) = 171,
    CallMethodDescriptorFast(OpargType<crate::Oparg>) = 172,
    CallMethodDescriptorFastWithKeywords(OpargType<crate::Oparg>) = 173,
    CallMethodDescriptorNoargs(OpargType<crate::Oparg>) = 174,
    CallMethodDescriptorO(OpargType<crate::Oparg>) = 175,
    CallNonPyGeneral(OpargType<crate::Oparg>) = 176,
    CallPyExactArgs(OpargType<crate::Oparg>) = 177,
    CallPyGeneral(OpargType<crate::Oparg>) = 178,
    CallStr1(OpargType<crate::Oparg>) = 179,
    CallTuple1(OpargType<crate::Oparg>) = 180,
    CallType1(OpargType<crate::Oparg>) = 181,
    CheckEgMatch = 6,
    CheckExcMatch = 7,
    CleanupThrow = 8,
    CompareOp(OpargType<crate::Oparg>) = 58,
    CompareOpFloat(OpargType<crate::Oparg>) = 182,
    CompareOpInt(OpargType<crate::Oparg>) = 183,
    CompareOpStr(OpargType<crate::Oparg>) = 184,
    ContainsOp(OpargType<crate::Oparg>) = 59,
    ContainsOpDict(OpargType<crate::Oparg>) = 185,
    ContainsOpSet(OpargType<crate::Oparg>) = 186,
    ConvertValue(OpargType<crate::Oparg>) = 60,
    Copy(OpargType<crate::Oparg>) = 61,
    CopyFreeVars(OpargType<crate::Oparg>) = 62,
    DeleteAttr(OpargType<crate::NameIdxOparg>) = 63,
    DeleteDeref(OpargType<crate::Oparg>) = 64,
    DeleteFast(OpargType<crate::Oparg>) = 65,
    DeleteGlobal(OpargType<crate::NameIdxOparg>) = 66,
    DeleteName(OpargType<crate::NameIdxOparg>) = 67,
    DeleteSubscr = 9,
    DictMerge(OpargType<crate::Oparg>) = 68,
    DictUpdate(OpargType<crate::Oparg>) = 69,
    EndAsyncFor = 10,
    EndFor = 11,
    EndSend = 12,
    EnterExecutor(OpargType<crate::Oparg>) = 70,
    ExitInitCheck = 13,
    ExtendedArg(OpargType<crate::Oparg>) = 71,
    FormatSimple = 14,
    FormatWithSpec = 15,
    ForIter(OpargType<crate::DeltaOparg>) = 72,
    ForIterGen(OpargType<crate::DeltaOparg>) = 187,
    ForIterList(OpargType<crate::DeltaOparg>) = 188,
    ForIterRange(OpargType<crate::DeltaOparg>) = 189,
    ForIterTuple(OpargType<crate::DeltaOparg>) = 190,
    GetAiter = 16,
    GetAnext = 18,
    GetAwaitable(OpargType<crate::Oparg>) = 73,
    GetIter = 19,
    GetLen = 20,
    GetYieldFromIter = 21,
    ImportFrom(OpargType<crate::NameIdxOparg>) = 74,
    ImportName(OpargType<crate::NameIdxOparg>) = 75,
    InstrumentedCall(OpargType<crate::Oparg>) = 244,
    InstrumentedCallFunctionEx = 246,
    InstrumentedCallKw(OpargType<crate::Oparg>) = 245,
    InstrumentedEndFor = 237,
    InstrumentedEndSend = 238,
    InstrumentedForIter(OpargType<crate::Oparg>) = 243,
    InstrumentedInstruction = 247,
    InstrumentedJumpBackward(OpargType<crate::Oparg>) = 249,
    InstrumentedJumpForward(OpargType<crate::Oparg>) = 248,
    InstrumentedLine = 254,
    InstrumentedLoadSuperAttr(OpargType<crate::Oparg>) = 242,
    InstrumentedPopJumpIfFalse(OpargType<crate::Oparg>) = 251,
    InstrumentedPopJumpIfNone(OpargType<crate::Oparg>) = 252,
    InstrumentedPopJumpIfNotNone(OpargType<crate::Oparg>) = 253,
    InstrumentedPopJumpIfTrue(OpargType<crate::Oparg>) = 250,
    InstrumentedResume(OpargType<crate::Oparg>) = 236,
    InstrumentedReturnConst(OpargType<crate::ConstIdxOparg>) = 240,
    InstrumentedReturnValue = 239,
    InstrumentedYieldValue(OpargType<crate::Oparg>) = 241,
    InterpreterExit = 22,
    IsOp(OpargType<crate::Oparg>) = 76,
    JumpBackward(OpargType<crate::DeltaOparg>) = 77,
    JumpBackwardNoInterrupt(OpargType<crate::DeltaOparg>) = 78,
    JumpForward(OpargType<crate::DeltaOparg>) = 79,
    ListAppend(OpargType<crate::Oparg>) = 80,
    ListExtend(OpargType<crate::Oparg>) = 81,
    LoadAssertionError = 23,
    LoadAttr(OpargType<crate::NameIdxOparg>) = 82,
    LoadAttrClass(OpargType<crate::NameIdxOparg>) = 191,
    LoadAttrGetattributeOverridden(OpargType<crate::NameIdxOparg>) = 192,
    LoadAttrInstanceValue(OpargType<crate::NameIdxOparg>) = 193,
    LoadAttrMethodLazyDict(OpargType<crate::NameIdxOparg>) = 194,
    LoadAttrMethodNoDict(OpargType<crate::NameIdxOparg>) = 195,
    LoadAttrMethodWithValues(OpargType<crate::NameIdxOparg>) = 196,
    LoadAttrModule(OpargType<crate::NameIdxOparg>) = 197,
    LoadAttrNondescriptorNoDict(OpargType<crate::NameIdxOparg>) = 198,
    LoadAttrNondescriptorWithValues(OpargType<crate::NameIdxOparg>) = 199,
    LoadAttrProperty(OpargType<crate::NameIdxOparg>) = 200,
    LoadAttrSlot(OpargType<crate::NameIdxOparg>) = 201,
    LoadAttrWithHint(OpargType<crate::NameIdxOparg>) = 202,
    LoadBuildClass = 24,
    LoadConst(OpargType<crate::ConstIdxOparg>) = 83,
    LoadDeref(OpargType<crate::Oparg>) = 84,
    LoadFast(OpargType<crate::Oparg>) = 85,
    LoadFastAndClear(OpargType<crate::Oparg>) = 86,
    LoadFastCheck(OpargType<crate::Oparg>) = 87,
    LoadFastLoadFast(OpargType<crate::Oparg>) = 88,
    LoadFromDictOrDeref(OpargType<crate::Oparg>) = 89,
    LoadFromDictOrGlobals(OpargType<crate::NameIdxOparg>) = 90,
    LoadGlobal(OpargType<crate::NameIdxOparg>) = 91,
    LoadGlobalBuiltin(OpargType<crate::NameIdxOparg>) = 203,
    LoadGlobalModule(OpargType<crate::NameIdxOparg>) = 204,
    LoadLocals = 25,
    LoadName(OpargType<crate::NameIdxOparg>) = 92,
    LoadSuperAttr(OpargType<crate::NameIdxOparg>) = 93,
    LoadSuperAttrAttr(OpargType<crate::NameIdxOparg>) = 205,
    LoadSuperAttrMethod(OpargType<crate::NameIdxOparg>) = 206,
    MakeCell(OpargType<crate::Oparg>) = 94,
    MakeFunction = 26,
    MapAdd(OpargType<crate::Oparg>) = 95,
    MatchClass(OpargType<crate::Oparg>) = 96,
    MatchKeys = 27,
    MatchMapping = 28,
    MatchSequence = 29,
    Nop = 30,
    PopExcept = 31,
    PopJumpIfFalse(OpargType<crate::DeltaOparg>) = 97,
    PopJumpIfNone(OpargType<crate::DeltaOparg>) = 98,
    PopJumpIfNotNone(OpargType<crate::DeltaOparg>) = 99,
    PopJumpIfTrue(OpargType<crate::DeltaOparg>) = 100,
    PopTop = 32,
    PushExcInfo = 33,
    PushNull = 34,
    RaiseVarargs(OpargType<crate::RaiseVarArgsOparg>) = 101,
    Reraise(OpargType<crate::Oparg>) = 102,
    Reserved = 17,
    Resume(OpargType<crate::ResumeOparg>) = 149,
    ResumeCheck(OpargType<crate::ResumeOparg>) = 207,
    ReturnConst(OpargType<crate::ConstIdxOparg>) = 103,
    ReturnGenerator = 35,
    ReturnValue = 36,
    Send(OpargType<crate::DeltaOparg>) = 104,
    SendGen(OpargType<crate::DeltaOparg>) = 208,
    SetupAnnotations = 37,
    SetAdd(OpargType<crate::Oparg>) = 105,
    SetFunctionAttribute(OpargType<crate::Oparg>) = 106,
    SetUpdate(OpargType<crate::Oparg>) = 107,
    StoreAttr(OpargType<crate::NameIdxOparg>) = 108,
    StoreAttrInstanceValue(OpargType<crate::NameIdxOparg>) = 209,
    StoreAttrSlot(OpargType<crate::NameIdxOparg>) = 210,
    StoreAttrWithHint(OpargType<crate::NameIdxOparg>) = 211,
    StoreDeref(OpargType<crate::Oparg>) = 109,
    StoreFast(OpargType<crate::Oparg>) = 110,
    StoreFastLoadFast(OpargType<crate::Oparg>) = 111,
    StoreFastStoreFast(OpargType<crate::Oparg>) = 112,
    StoreGlobal(OpargType<crate::NameIdxOparg>) = 113,
    StoreName(OpargType<crate::NameIdxOparg>) = 114,
    StoreSlice = 38,
    StoreSubscr = 39,
    StoreSubscrDict = 212,
    StoreSubscrListInt = 213,
    Swap(OpargType<crate::Oparg>) = 115,
    ToBool = 40,
    ToBoolAlwaysTrue = 214,
    ToBoolBool = 215,
    ToBoolInt = 216,
    ToBoolList = 217,
    ToBoolNone = 218,
    ToBoolStr = 219,
    UnaryInvert = 41,
    UnaryNegative = 42,
    UnaryNot = 43,
    UnpackEx(OpargType<crate::UnpackExOparg>) = 116,
    UnpackSequence(OpargType<crate::Oparg>) = 117,
    UnpackSequenceList(OpargType<crate::Oparg>) = 220,
    UnpackSequenceTuple(OpargType<crate::Oparg>) = 221,
    UnpackSequenceTwoTuple(OpargType<crate::Oparg>) = 222,
    WithExceptStart = 44,
    YieldValue(OpargType<crate::Oparg>) = 118,
}

impl RealInstruction {
    pub const fn deopt(self) -> Option<Self> {
        // Should we group these?
        Some(match self {
            Self::BinaryOpAddFloat(typ) => Self::BinaryOp(typ),
            Self::BinaryOpAddInt(typ) => Self::BinaryOp(typ),
            Self::BinaryOpAddUnicode(typ) => Self::BinaryOp(typ),
            Self::BinaryOpInplaceAddUnicode(typ) => Self::BinaryOp(typ),
            Self::BinaryOpMultiplyFloat(typ) => Self::BinaryOp(typ),
            Self::BinaryOpMultiplyInt(typ) => Self::BinaryOp(typ),
            Self::BinaryOpSubtractFloat(typ) => Self::BinaryOp(typ),
            Self::BinaryOpSubtractInt(typ) => Self::BinaryOp(typ),
            Self::BinarySubscrDict => Self::BinarySubscr,
            Self::BinarySubscrGetitem => Self::BinarySubscr,
            Self::BinarySubscrListInt => Self::BinarySubscr,
            Self::BinarySubscrStrInt => Self::BinarySubscr,
            Self::BinarySubscrTupleInt => Self::BinarySubscr,
            Self::CallAllocAndEnterInit(typ) => Self::Call(typ),
            Self::CallBoundMethodExactArgs(typ) => Self::Call(typ),
            Self::CallBoundMethodGeneral(typ) => Self::Call(typ),
            Self::CallBuiltinClass(typ) => Self::Call(typ),
            Self::CallBuiltinFast(typ) => Self::Call(typ),
            Self::CallBuiltinFastWithKeywords(typ) => Self::Call(typ),
            Self::CallBuiltinO(typ) => Self::Call(typ),
            Self::CallIsinstance(typ) => Self::Call(typ),
            Self::CallLen(typ) => Self::Call(typ),
            Self::CallListAppend(typ) => Self::Call(typ),
            Self::CallMethodDescriptorFast(typ) => Self::Call(typ),
            Self::CallMethodDescriptorFastWithKeywords(typ) => Self::Call(typ),
            Self::CallMethodDescriptorNoargs(typ) => Self::Call(typ),
            Self::CallMethodDescriptorO(typ) => Self::Call(typ),
            Self::CallNonPyGeneral(typ) => Self::Call(typ),
            Self::CallPyExactArgs(typ) => Self::Call(typ),
            Self::CallPyGeneral(typ) => Self::Call(typ),
            Self::CallStr1(typ) => Self::Call(typ),
            Self::CallTuple1(typ) => Self::Call(typ),
            Self::CallType1(typ) => Self::Call(typ),
            Self::CompareOpFloat(typ) => Self::CompareOp(typ),
            Self::CompareOpInt(typ) => Self::CompareOp(typ),
            Self::CompareOpStr(typ) => Self::CompareOp(typ),
            Self::ContainsOpDict(typ) => Self::ContainsOp(typ),
            Self::ContainsOpSet(typ) => Self::ContainsOp(typ),
            Self::ForIterGen(typ) => Self::ForIter(typ),
            Self::ForIterList(typ) => Self::ForIter(typ),
            Self::ForIterRange(typ) => Self::ForIter(typ),
            Self::ForIterTuple(typ) => Self::ForIter(typ),
            Self::LoadAttrClass(typ) => Self::LoadAttr(typ),
            Self::LoadAttrGetattributeOverridden(typ) => Self::LoadAttr(typ),
            Self::LoadAttrInstanceValue(typ) => Self::LoadAttr(typ),
            Self::LoadAttrMethodLazyDict(typ) => Self::LoadAttr(typ),
            Self::LoadAttrMethodNoDict(typ) => Self::LoadAttr(typ),
            Self::LoadAttrMethodWithValues(typ) => Self::LoadAttr(typ),
            Self::LoadAttrModule(typ) => Self::LoadAttr(typ),
            Self::LoadAttrNondescriptorNoDict(typ) => Self::LoadAttr(typ),
            Self::LoadAttrNondescriptorWithValues(typ) => Self::LoadAttr(typ),
            Self::LoadAttrProperty(typ) => Self::LoadAttr(typ),
            Self::LoadAttrSlot(typ) => Self::LoadAttr(typ),
            Self::LoadAttrWithHint(typ) => Self::LoadAttr(typ),
            Self::LoadGlobalBuiltin(typ) => Self::LoadGlobal(typ),
            Self::LoadGlobalModule(typ) => Self::LoadGlobal(typ),
            Self::LoadSuperAttrAttr(typ) => Self::LoadSuperAttr(typ),
            Self::LoadSuperAttrMethod(typ) => Self::LoadSuperAttr(typ),
            Self::ResumeCheck(typ) => Self::Resume(typ),
            Self::SendGen(typ) => Self::Send(typ),
            Self::StoreAttrInstanceValue(typ) => Self::StoreAttr(typ),
            Self::StoreAttrSlot(typ) => Self::StoreAttr(typ),
            Self::StoreAttrWithHint(typ) => Self::StoreAttr(typ),
            Self::StoreSubscrDict => Self::StoreSubscr,
            Self::StoreSubscrListInt => Self::StoreSubscr,
            Self::ToBoolAlwaysTrue => Self::ToBool,
            Self::ToBoolBool => Self::ToBool,
            Self::ToBoolInt => Self::ToBool,
            Self::ToBoolList => Self::ToBool,
            Self::ToBoolNone => Self::ToBool,
            Self::ToBoolStr => Self::ToBool,
            Self::UnpackSequenceList(typ) => Self::UnpackSequence(typ),
            Self::UnpackSequenceTuple(typ) => Self::UnpackSequence(typ),
            Self::UnpackSequenceTwoTuple(typ) => Self::UnpackSequence(typ),
            _ => return None,
        })
    }

    /// Whether opcode ID have 'HAS_ARG_FLAG' set.
    #[must_use]
    pub const fn has_arg(self) -> bool {
        matches!(
            self,
            Self::BinaryOp(_)
                | Self::BuildConstKeyMap(_)
                | Self::BuildList(_)
                | Self::BuildMap(_)
                | Self::BuildSet(_)
                | Self::BuildSlice(_)
                | Self::BuildString(_)
                | Self::BuildTuple(_)
                | Self::Call(_)
                | Self::CallAllocAndEnterInit(_)
                | Self::CallBoundMethodExactArgs(_)
                | Self::CallBoundMethodGeneral(_)
                | Self::CallBuiltinClass(_)
                | Self::CallBuiltinFast(_)
                | Self::CallBuiltinFastWithKeywords(_)
                | Self::CallBuiltinO(_)
                | Self::CallFunctionEx(_)
                | Self::CallIntrinsic1(_)
                | Self::CallIntrinsic2(_)
                | Self::CallIsinstance(_)
                | Self::CallKw(_)
                | Self::CallLen(_)
                | Self::CallListAppend(_)
                | Self::CallMethodDescriptorFast(_)
                | Self::CallMethodDescriptorFastWithKeywords(_)
                | Self::CallMethodDescriptorNoargs(_)
                | Self::CallMethodDescriptorO(_)
                | Self::CallNonPyGeneral(_)
                | Self::CallPyExactArgs(_)
                | Self::CallPyGeneral(_)
                | Self::CallStr1(_)
                | Self::CallTuple1(_)
                | Self::CallType1(_)
                | Self::CompareOp(_)
                | Self::CompareOpFloat(_)
                | Self::CompareOpInt(_)
                | Self::CompareOpStr(_)
                | Self::ContainsOp(_)
                | Self::ContainsOpDict(_)
                | Self::ContainsOpSet(_)
                | Self::ConvertValue(_)
                | Self::Copy(_)
                | Self::CopyFreeVars(_)
                | Self::DeleteAttr(_)
                | Self::DeleteDeref(_)
                | Self::DeleteFast(_)
                | Self::DeleteGlobal(_)
                | Self::DeleteName(_)
                | Self::DictMerge(_)
                | Self::DictUpdate(_)
                | Self::EnterExecutor(_)
                | Self::ExtendedArg(_)
                | Self::ForIter(_)
                | Self::ForIterGen(_)
                | Self::ForIterList(_)
                | Self::ForIterRange(_)
                | Self::ForIterTuple(_)
                | Self::GetAwaitable(_)
                | Self::ImportFrom(_)
                | Self::ImportName(_)
                | Self::InstrumentedCall(_)
                | Self::InstrumentedCallKw(_)
                | Self::InstrumentedForIter(_)
                | Self::InstrumentedJumpBackward(_)
                | Self::InstrumentedJumpForward(_)
                | Self::InstrumentedLoadSuperAttr(_)
                | Self::InstrumentedPopJumpIfFalse(_)
                | Self::InstrumentedPopJumpIfNone(_)
                | Self::InstrumentedPopJumpIfNotNone(_)
                | Self::InstrumentedPopJumpIfTrue(_)
                | Self::InstrumentedResume(_)
                | Self::InstrumentedReturnConst(_)
                | Self::InstrumentedYieldValue(_)
                | Self::IsOp(_)
                | Self::JumpBackward(_)
                | Self::JumpBackwardNoInterrupt(_)
                | Self::JumpForward(_)
                | Self::ListAppend(_)
                | Self::ListExtend(_)
                | Self::LoadAttr(_)
                | Self::LoadAttrClass(_)
                | Self::LoadAttrGetattributeOverridden(_)
                | Self::LoadAttrInstanceValue(_)
                | Self::LoadAttrMethodLazyDict(_)
                | Self::LoadAttrMethodNoDict(_)
                | Self::LoadAttrMethodWithValues(_)
                | Self::LoadAttrModule(_)
                | Self::LoadAttrNondescriptorNoDict(_)
                | Self::LoadAttrNondescriptorWithValues(_)
                | Self::LoadAttrProperty(_)
                | Self::LoadAttrSlot(_)
                | Self::LoadAttrWithHint(_)
                | Self::LoadConst(_)
                | Self::LoadDeref(_)
                | Self::LoadFast(_)
                | Self::LoadFastAndClear(_)
                | Self::LoadFastCheck(_)
                | Self::LoadFastLoadFast(_)
                | Self::LoadFromDictOrDeref(_)
                | Self::LoadFromDictOrGlobals(_)
                | Self::LoadGlobal(_)
                | Self::LoadGlobalBuiltin(_)
                | Self::LoadGlobalModule(_)
                | Self::LoadName(_)
                | Self::LoadSuperAttr(_)
                | Self::LoadSuperAttrAttr(_)
                | Self::LoadSuperAttrMethod(_)
                | Self::MakeCell(_)
                | Self::MapAdd(_)
                | Self::MatchClass(_)
                | Self::PopJumpIfFalse(_)
                | Self::PopJumpIfNone(_)
                | Self::PopJumpIfNotNone(_)
                | Self::PopJumpIfTrue(_)
                | Self::RaiseVarargs(_)
                | Self::Reraise(_)
                | Self::Resume(_)
                | Self::ReturnConst(_)
                | Self::Send(_)
                | Self::SendGen(_)
                | Self::SetAdd(_)
                | Self::SetFunctionAttribute(_)
                | Self::SetUpdate(_)
                | Self::StoreAttr(_)
                | Self::StoreAttrWithHint(_)
                | Self::StoreDeref(_)
                | Self::StoreFast(_)
                | Self::StoreFastLoadFast(_)
                | Self::StoreFastStoreFast(_)
                | Self::StoreGlobal(_)
                | Self::StoreName(_)
                | Self::Swap(_)
                | Self::UnpackEx(_)
                | Self::UnpackSequence(_)
                | Self::UnpackSequenceList(_)
                | Self::UnpackSequenceTuple(_)
                | Self::UnpackSequenceTwoTuple(_)
                | Self::YieldValue(_)
        )
    }

    /// Whether opcode ID have 'HAS_CONST_FLAG' set.
    #[must_use]
    pub const fn has_const(self) -> bool {
        matches!(
            self,
            Self::InstrumentedReturnConst(_) | Self::LoadConst(_) | Self::ReturnConst(_)
        )
    }

    /// Whether opcode ID have 'HAS_PURE_FLAG' set.
    #[must_use]
    pub const fn has_exc(self) -> bool {
        matches!(
            self,
            Self::Copy(_)
                | Self::EndFor
                | Self::EndSend
                | Self::InstrumentedLine
                | Self::LoadConst(_)
                | Self::LoadFast(_)
                | Self::Nop
                | Self::PopTop
                | Self::PushNull
                | Self::Swap(_)
                | Self::UnaryNot
        )
    }

    /// Whether opcode ID have 'HAS_FREE_FLAG' set.
    #[must_use]
    pub const fn has_free(self) -> bool {
        matches!(
            self,
            Self::DeleteDeref(_)
                | Self::LoadDeref(_)
                | Self::LoadFromDictOrDeref(_)
                | Self::MakeCell(_)
                | Self::StoreDeref(_)
        )
    }

    /// Whether opcode ID have 'HAS_JUMP_FLAG' set.
    #[must_use]
    pub const fn has_jump(self) -> bool {
        matches!(
            self,
            Self::ForIter(_)
                | Self::ForIterList(_)
                | Self::ForIterRange(_)
                | Self::ForIterTuple(_)
                | Self::JumpBackward(_)
                | Self::JumpBackwardNoInterrupt(_)
                | Self::JumpForward(_)
                | Self::PopJumpIfFalse(_)
                | Self::PopJumpIfNone(_)
                | Self::PopJumpIfNotNone(_)
                | Self::PopJumpIfTrue(_)
                | Self::Send(_)
        )
    }

    /// Whether opcode ID have 'HAS_LOCAL_FLAG' set.
    #[must_use]
    pub const fn has_local(self) -> bool {
        matches!(
            self,
            Self::BinaryOpInplaceAddUnicode(_)
                | Self::DeleteFast(_)
                | Self::LoadFast(_)
                | Self::LoadFastAndClear(_)
                | Self::LoadFastCheck(_)
                | Self::LoadFastLoadFast(_)
                | Self::StoreFast(_)
                | Self::StoreFastLoadFast(_)
                | Self::StoreFastStoreFast(_)
        )
    }

    /// Whether opcode ID have 'HAS_NAME_FLAG' set.
    #[must_use]
    pub const fn has_name(self) -> bool {
        matches!(
            self,
            Self::DeleteAttr(_)
                | Self::DeleteGlobal(_)
                | Self::DeleteName(_)
                | Self::ImportFrom(_)
                | Self::ImportName(_)
                | Self::LoadAttr(_)
                | Self::LoadAttrGetattributeOverridden(_)
                | Self::LoadAttrWithHint(_)
                | Self::LoadFromDictOrGlobals(_)
                | Self::LoadGlobal(_)
                | Self::LoadName(_)
                | Self::LoadSuperAttr(_)
                | Self::LoadSuperAttrAttr(_)
                | Self::LoadSuperAttrMethod(_)
                | Self::StoreAttr(_)
                | Self::StoreAttrWithHint(_)
                | Self::StoreGlobal(_)
                | Self::StoreName(_)
        )
    }

    /// How many items should be popped from the stack.
    pub(crate) const fn num_popped(self, oparg: Oparg) -> u32 {
        match self {
            Self::BeforeAsyncWith => 1,
            Self::BeforeWith => 1,
            Self::BinaryOp(_) => 2,
            Self::BinaryOpAddFloat(_) => 2,
            Self::BinaryOpAddInt(_) => 2,
            Self::BinaryOpAddUnicode(_) => 2,
            Self::BinaryOpInplaceAddUnicode(_) => 2,
            Self::BinaryOpMultiplyFloat(_) => 2,
            Self::BinaryOpMultiplyInt(_) => 2,
            Self::BinaryOpSubtractFloat(_) => 2,
            Self::BinaryOpSubtractInt(_) => 2,
            Self::BinarySlice => 3,
            Self::BinarySubscr => 2,
            Self::BinarySubscrDict => 2,
            Self::BinarySubscrGetitem => 2,
            Self::BinarySubscrListInt => 2,
            Self::BinarySubscrStrInt => 2,
            Self::BinarySubscrTupleInt => 2,
            Self::BuildConstKeyMap(_) => 1 + *oparg,
            Self::BuildList(_) => *oparg,
            Self::BuildMap(_) => *oparg * 2,
            Self::BuildSet(_) => *oparg,
            Self::BuildSlice(_) => 2 + (if *oparg == 3 { 1 } else { 0 }),
            Self::BuildString(_) => *oparg,
            Self::BuildTuple(_) => *oparg,
            Self::Cache => 0,
            Self::Call(_) => 2 + *oparg,
            Self::CallAllocAndEnterInit(_) => 2 + *oparg,
            Self::CallBoundMethodExactArgs(_) => 2 + *oparg,
            Self::CallBoundMethodGeneral(_) => 2 + *oparg,
            Self::CallBuiltinClass(_) => 2 + *oparg,
            Self::CallBuiltinFast(_) => 2 + *oparg,
            Self::CallBuiltinFastWithKeywords(_) => 2 + *oparg,
            Self::CallBuiltinO(_) => 2 + *oparg,
            Self::CallFunctionEx(_) => 3 + (*oparg & 1),
            Self::CallIntrinsic1(_) => 1,
            Self::CallIntrinsic2(_) => 2,
            Self::CallIsinstance(_) => 2 + *oparg,
            Self::CallKw(_) => 3 + *oparg,
            Self::CallLen(_) => 2 + *oparg,
            Self::CallListAppend(_) => 3,
            Self::CallMethodDescriptorFast(_) => 2 + *oparg,
            Self::CallMethodDescriptorFastWithKeywords(_) => 2 + *oparg,
            Self::CallMethodDescriptorNoargs(_) => 2 + *oparg,
            Self::CallMethodDescriptorO(_) => 2 + *oparg,
            Self::CallNonPyGeneral(_) => 2 + *oparg,
            Self::CallPyExactArgs(_) => 2 + *oparg,
            Self::CallPyGeneral(_) => 2 + *oparg,
            Self::CallStr1(_) => 3,
            Self::CallTuple1(_) => 3,
            Self::CallType1(_) => 3,
            Self::CheckEgMatch => 2,
            Self::CheckExcMatch => 2,
            Self::CleanupThrow => 3,
            Self::CompareOp(_) => 2,
            Self::CompareOpFloat(_) => 2,
            Self::CompareOpInt(_) => 2,
            Self::CompareOpStr(_) => 2,
            Self::ContainsOp(_) => 2,
            Self::ContainsOpDict(_) => 2,
            Self::ContainsOpSet(_) => 2,
            Self::ConvertValue(_) => 1,
            Self::Copy(_) => 1 + (*oparg - 1),
            Self::CopyFreeVars(_) => 0,
            Self::DeleteAttr(_) => 1,
            Self::DeleteDeref(_) => 0,
            Self::DeleteFast(_) => 0,
            Self::DeleteGlobal(_) => 0,
            Self::DeleteName(_) => 0,
            Self::DeleteSubscr => 2,
            Self::DictMerge(_) => 5 + (*oparg - 1),
            Self::DictUpdate(_) => 2 + (*oparg - 1),
            Self::EndAsyncFor => 2,
            Self::EndFor => 1,
            Self::EndSend => 2,
            Self::EnterExecutor(_) => 0,
            Self::ExitInitCheck => 1,
            Self::ExtendedArg(_) => 0,
            Self::FormatSimple => 1,
            Self::FormatWithSpec => 2,
            Self::ForIter(_) => 1,
            Self::ForIterGen(_) => 1,
            Self::ForIterList(_) => 1,
            Self::ForIterRange(_) => 1,
            Self::ForIterTuple(_) => 1,
            Self::GetAiter => 1,
            Self::GetAnext => 1,
            Self::GetAwaitable(_) => 1,
            Self::GetIter => 1,
            Self::GetLen => 1,
            Self::GetYieldFromIter => 1,
            Self::ImportFrom(_) => 1,
            Self::ImportName(_) => 2,
            Self::InstrumentedCall(_) => 0,
            Self::InstrumentedCallFunctionEx => 0,
            Self::InstrumentedCallKw(_) => 0,
            Self::InstrumentedEndFor => 2,
            Self::InstrumentedEndSend => 2,
            Self::InstrumentedForIter(_) => 0,
            Self::InstrumentedInstruction => 0,
            Self::InstrumentedJumpBackward(_) => 0,
            Self::InstrumentedJumpForward(_) => 0,
            Self::InstrumentedLine => 0,
            Self::InstrumentedLoadSuperAttr(_) => 3,
            Self::InstrumentedPopJumpIfFalse(_) => 0,
            Self::InstrumentedPopJumpIfNone(_) => 0,
            Self::InstrumentedPopJumpIfNotNone(_) => 0,
            Self::InstrumentedPopJumpIfTrue(_) => 0,
            Self::InstrumentedResume(_) => 0,
            Self::InstrumentedReturnConst(_) => 0,
            Self::InstrumentedReturnValue => 1,
            Self::InstrumentedYieldValue(_) => 1,
            Self::InterpreterExit => 1,
            Self::IsOp(_) => 2,
            Self::JumpBackward(_) => 0,
            Self::JumpBackwardNoInterrupt(_) => 0,
            Self::JumpForward(_) => 0,
            Self::ListAppend(_) => 2 + (*oparg - 1),
            Self::ListExtend(_) => 2 + (*oparg - 1),
            Self::LoadAssertionError => 0,
            Self::LoadAttr(_) => 1,
            Self::LoadAttrClass(_) => 1,
            Self::LoadAttrGetattributeOverridden(_) => 1,
            Self::LoadAttrInstanceValue(_) => 1,
            Self::LoadAttrMethodLazyDict(_) => 1,
            Self::LoadAttrMethodNoDict(_) => 1,
            Self::LoadAttrMethodWithValues(_) => 1,
            Self::LoadAttrModule(_) => 1,
            Self::LoadAttrNondescriptorNoDict(_) => 1,
            Self::LoadAttrNondescriptorWithValues(_) => 1,
            Self::LoadAttrProperty(_) => 1,
            Self::LoadAttrSlot(_) => 1,
            Self::LoadAttrWithHint(_) => 1,
            Self::LoadBuildClass => 0,
            Self::LoadConst(_) => 0,
            Self::LoadDeref(_) => 0,
            Self::LoadFast(_) => 0,
            Self::LoadFastAndClear(_) => 0,
            Self::LoadFastCheck(_) => 0,
            Self::LoadFastLoadFast(_) => 0,
            Self::LoadFromDictOrDeref(_) => 1,
            Self::LoadFromDictOrGlobals(_) => 1,
            Self::LoadGlobal(_) => 0,
            Self::LoadGlobalBuiltin(_) => 0,
            Self::LoadGlobalModule(_) => 0,
            Self::LoadLocals => 0,
            Self::LoadName(_) => 0,
            Self::LoadSuperAttr(_) => 3,
            Self::LoadSuperAttrAttr(_) => 3,
            Self::LoadSuperAttrMethod(_) => 3,
            Self::MakeCell(_) => 0,
            Self::MakeFunction => 1,
            Self::MapAdd(_) => 3 + (*oparg - 1),
            Self::MatchClass(_) => 3,
            Self::MatchKeys => 2,
            Self::MatchMapping => 1,
            Self::MatchSequence => 1,
            Self::Nop => 0,
            Self::PopExcept => 1,
            Self::PopJumpIfFalse(_) => 1,
            Self::PopJumpIfNone(_) => 1,
            Self::PopJumpIfNotNone(_) => 1,
            Self::PopJumpIfTrue(_) => 1,
            Self::PopTop => 1,
            Self::PushExcInfo => 1,
            Self::PushNull => 0,
            Self::RaiseVarargs(_) => *oparg,
            Self::Reraise(_) => 1 + *oparg,
            Self::Reserved => 0,
            Self::Resume(_) => 0,
            Self::ResumeCheck(_) => 0,
            Self::ReturnConst(_) => 0,
            Self::ReturnGenerator => 0,
            Self::ReturnValue => 1,
            Self::Send(_) => 2,
            Self::SendGen(_) => 2,
            Self::SetupAnnotations => 0,
            Self::SetAdd(_) => 2 + (*oparg - 1),
            Self::SetFunctionAttribute(_) => 2,
            Self::SetUpdate(_) => 2 + (*oparg - 1),
            Self::StoreAttr(_) => 2,
            Self::StoreAttrInstanceValue(_) => 2,
            Self::StoreAttrSlot(_) => 2,
            Self::StoreAttrWithHint(_) => 2,
            Self::StoreDeref(_) => 1,
            Self::StoreFast(_) => 1,
            Self::StoreFastLoadFast(_) => 1,
            Self::StoreFastStoreFast(_) => 2,
            Self::StoreGlobal(_) => 1,
            Self::StoreName(_) => 1,
            Self::StoreSlice => 4,
            Self::StoreSubscr => 3,
            Self::StoreSubscrDict => 3,
            Self::StoreSubscrListInt => 3,
            Self::Swap(_) => 2 + (*oparg - 2),
            Self::ToBool => 1,
            Self::ToBoolAlwaysTrue => 1,
            Self::ToBoolBool => 1,
            Self::ToBoolInt => 1,
            Self::ToBoolList => 1,
            Self::ToBoolNone => 1,
            Self::ToBoolStr => 1,
            Self::UnaryInvert => 1,
            Self::UnaryNegative => 1,
            Self::UnaryNot => 1,
            Self::UnpackEx(_) => 1,
            Self::UnpackSequence(_) => 1,
            Self::UnpackSequenceList(_) => 1,
            Self::UnpackSequenceTuple(_) => 1,
            Self::UnpackSequenceTwoTuple(_) => 1,
            Self::WithExceptStart => 4,
            Self::YieldValue(_) => 1,
        }
    }

    /// How many items should be pushed on the stack.
    pub(crate) const fn num_pushed(self, oparg: Oparg) -> u32 {
        match self {
            Self::BeforeAsyncWith => 2,
            Self::BeforeWith => 2,
            Self::BinaryOp(_) => 1,
            Self::BinaryOpAddFloat(_) => 1,
            Self::BinaryOpAddInt(_) => 1,
            Self::BinaryOpAddUnicode(_) => 1,
            Self::BinaryOpInplaceAddUnicode(_) => 0,
            Self::BinaryOpMultiplyFloat(_) => 1,
            Self::BinaryOpMultiplyInt(_) => 1,
            Self::BinaryOpSubtractFloat(_) => 1,
            Self::BinaryOpSubtractInt(_) => 1,
            Self::BinarySlice => 1,
            Self::BinarySubscr => 1,
            Self::BinarySubscrDict => 1,
            Self::BinarySubscrGetitem => 1,
            Self::BinarySubscrListInt => 1,
            Self::BinarySubscrStrInt => 1,
            Self::BinarySubscrTupleInt => 1,
            Self::BuildConstKeyMap(_) => 1,
            Self::BuildList(_) => 1,
            Self::BuildMap(_) => 1,
            Self::BuildSet(_) => 1,
            Self::BuildSlice(_) => 1,
            Self::BuildString(_) => 1,
            Self::BuildTuple(_) => 1,
            Self::Cache => 0,
            Self::Call(_) => 1,
            Self::CallAllocAndEnterInit(_) => 1,
            Self::CallBoundMethodExactArgs(_) => 0,
            Self::CallBoundMethodGeneral(_) => 0,
            Self::CallBuiltinClass(_) => 1,
            Self::CallBuiltinFast(_) => 1,
            Self::CallBuiltinFastWithKeywords(_) => 1,
            Self::CallBuiltinO(_) => 1,
            Self::CallFunctionEx(_) => 1,
            Self::CallIntrinsic1(_) => 1,
            Self::CallIntrinsic2(_) => 1,
            Self::CallIsinstance(_) => 1,
            Self::CallKw(_) => 1,
            Self::CallLen(_) => 1,
            Self::CallListAppend(_) => 1,
            Self::CallMethodDescriptorFast(_) => 1,
            Self::CallMethodDescriptorFastWithKeywords(_) => 1,
            Self::CallMethodDescriptorNoargs(_) => 1,
            Self::CallMethodDescriptorO(_) => 1,
            Self::CallNonPyGeneral(_) => 1,
            Self::CallPyExactArgs(_) => 0,
            Self::CallPyGeneral(_) => 0,
            Self::CallStr1(_) => 1,
            Self::CallTuple1(_) => 1,
            Self::CallType1(_) => 1,
            Self::CheckEgMatch => 2,
            Self::CheckExcMatch => 2,
            Self::CleanupThrow => 2,
            Self::CompareOp(_) => 1,
            Self::CompareOpFloat(_) => 1,
            Self::CompareOpInt(_) => 1,
            Self::CompareOpStr(_) => 1,
            Self::ContainsOp(_) => 1,
            Self::ContainsOpDict(_) => 1,
            Self::ContainsOpSet(_) => 1,
            Self::ConvertValue(_) => 1,
            Self::Copy(_) => 2 + (*oparg - 1),
            Self::CopyFreeVars(_) => 0,
            Self::DeleteAttr(_) => 0,
            Self::DeleteDeref(_) => 0,
            Self::DeleteFast(_) => 0,
            Self::DeleteGlobal(_) => 0,
            Self::DeleteName(_) => 0,
            Self::DeleteSubscr => 0,
            Self::DictMerge(_) => 4 + (*oparg - 1),
            Self::DictUpdate(_) => 1 + (*oparg - 1),
            Self::EndAsyncFor => 0,
            Self::EndFor => 0,
            Self::EndSend => 1,
            Self::EnterExecutor(_) => 0,
            Self::ExitInitCheck => 0,
            Self::ExtendedArg(_) => 0,
            Self::FormatSimple => 1,
            Self::FormatWithSpec => 1,
            Self::ForIter(_) => 2,
            Self::ForIterGen(_) => 1,
            Self::ForIterList(_) => 2,
            Self::ForIterRange(_) => 2,
            Self::ForIterTuple(_) => 2,
            Self::GetAiter => 1,
            Self::GetAnext => 2,
            Self::GetAwaitable(_) => 1,
            Self::GetIter => 1,
            Self::GetLen => 2,
            Self::GetYieldFromIter => 1,
            Self::ImportFrom(_) => 2,
            Self::ImportName(_) => 1,
            Self::InstrumentedCall(_) => 0,
            Self::InstrumentedCallFunctionEx => 0,
            Self::InstrumentedCallKw(_) => 0,
            Self::InstrumentedEndFor => 1,
            Self::InstrumentedEndSend => 1,
            Self::InstrumentedForIter(_) => 0,
            Self::InstrumentedInstruction => 0,
            Self::InstrumentedJumpBackward(_) => 0,
            Self::InstrumentedJumpForward(_) => 0,
            Self::InstrumentedLine => 0,
            Self::InstrumentedLoadSuperAttr(_) => 1 + (*oparg & 1),
            Self::InstrumentedPopJumpIfFalse(_) => 0,
            Self::InstrumentedPopJumpIfNone(_) => 0,
            Self::InstrumentedPopJumpIfNotNone(_) => 0,
            Self::InstrumentedPopJumpIfTrue(_) => 0,
            Self::InstrumentedResume(_) => 0,
            Self::InstrumentedReturnConst(_) => 0,
            Self::InstrumentedReturnValue => 0,
            Self::InstrumentedYieldValue(_) => 1,
            Self::InterpreterExit => 0,
            Self::IsOp(_) => 1,
            Self::JumpBackward(_) => 0,
            Self::JumpBackwardNoInterrupt(_) => 0,
            Self::JumpForward(_) => 0,
            Self::ListAppend(_) => 1 + (*oparg - 1),
            Self::ListExtend(_) => 1 + (*oparg - 1),
            Self::LoadAssertionError => 1,
            Self::LoadAttr(_) => 1 + (*oparg & 1),
            Self::LoadAttrClass(_) => 1 + (*oparg & 1),
            Self::LoadAttrGetattributeOverridden(_) => 1,
            Self::LoadAttrInstanceValue(_) => 1 + (*oparg & 1),
            Self::LoadAttrMethodLazyDict(_) => 2,
            Self::LoadAttrMethodNoDict(_) => 2,
            Self::LoadAttrMethodWithValues(_) => 2,
            Self::LoadAttrModule(_) => 1 + (*oparg & 1),
            Self::LoadAttrNondescriptorNoDict(_) => 1,
            Self::LoadAttrNondescriptorWithValues(_) => 1,
            Self::LoadAttrProperty(_) => 1,
            Self::LoadAttrSlot(_) => 1 + (*oparg & 1),
            Self::LoadAttrWithHint(_) => 1 + (*oparg & 1),
            Self::LoadBuildClass => 1,
            Self::LoadConst(_) => 1,
            Self::LoadDeref(_) => 1,
            Self::LoadFast(_) => 1,
            Self::LoadFastAndClear(_) => 1,
            Self::LoadFastCheck(_) => 1,
            Self::LoadFastLoadFast(_) => 2,
            Self::LoadFromDictOrDeref(_) => 1,
            Self::LoadFromDictOrGlobals(_) => 1,
            Self::LoadGlobal(_) => 1 + (*oparg & 1),
            Self::LoadGlobalBuiltin(_) => 1 + (*oparg & 1),
            Self::LoadGlobalModule(_) => 1 + (*oparg & 1),
            Self::LoadLocals => 1,
            Self::LoadName(_) => 1,
            Self::LoadSuperAttr(_) => 1 + (*oparg & 1),
            Self::LoadSuperAttrAttr(_) => 1,
            Self::LoadSuperAttrMethod(_) => 2,
            Self::MakeCell(_) => 0,
            Self::MakeFunction => 1,
            Self::MapAdd(_) => 1 + (*oparg - 1),
            Self::MatchClass(_) => 1,
            Self::MatchKeys => 3,
            Self::MatchMapping => 2,
            Self::MatchSequence => 2,
            Self::Nop => 0,
            Self::PopExcept => 0,
            Self::PopJumpIfFalse(_) => 0,
            Self::PopJumpIfNone(_) => 0,
            Self::PopJumpIfNotNone(_) => 0,
            Self::PopJumpIfTrue(_) => 0,
            Self::PopTop => 0,
            Self::PushExcInfo => 2,
            Self::PushNull => 1,
            Self::RaiseVarargs(_) => 0,
            Self::Reraise(_) => *oparg,
            Self::Reserved => 0,
            Self::Resume(_) => 0,
            Self::ResumeCheck(_) => 0,
            Self::ReturnConst(_) => 0,
            Self::ReturnGenerator => 1,
            Self::ReturnValue => 0,
            Self::Send(_) => 2,
            Self::SendGen(_) => 2,
            Self::SetupAnnotations => 0,
            Self::SetAdd(_) => 1 + (*oparg - 1),
            Self::SetFunctionAttribute(_) => 1,
            Self::SetUpdate(_) => 1 + (*oparg - 1),
            Self::StoreAttr(_) => 0,
            Self::StoreAttrInstanceValue(_) => 0,
            Self::StoreAttrSlot(_) => 0,
            Self::StoreAttrWithHint(_) => 0,
            Self::StoreDeref(_) => 0,
            Self::StoreFast(_) => 0,
            Self::StoreFastLoadFast(_) => 1,
            Self::StoreFastStoreFast(_) => 0,
            Self::StoreGlobal(_) => 0,
            Self::StoreName(_) => 0,
            Self::StoreSlice => 0,
            Self::StoreSubscr => 0,
            Self::StoreSubscrDict => 0,
            Self::StoreSubscrListInt => 0,
            Self::Swap(_) => 2 + (*oparg - 2),
            Self::ToBool => 1,
            Self::ToBoolAlwaysTrue => 1,
            Self::ToBoolBool => 1,
            Self::ToBoolInt => 1,
            Self::ToBoolList => 1,
            Self::ToBoolNone => 1,
            Self::ToBoolStr => 1,
            Self::UnaryInvert => 1,
            Self::UnaryNegative => 1,
            Self::UnaryNot => 1,
            Self::UnpackEx(_) => 1 + (*oparg >> 8) + (*oparg & 0xFF),
            Self::UnpackSequence(_) => *oparg,
            Self::UnpackSequenceList(_) => *oparg,
            Self::UnpackSequenceTuple(_) => *oparg,
            Self::UnpackSequenceTwoTuple(_) => 2,
            Self::WithExceptStart => 5,
            Self::YieldValue(_) => 1,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum PseudoInstruction {
    Jump(OpargType<crate::DeltaOparg>) = 256,
    JumpNoInterrupt(OpargType<crate::DeltaOparg>) = 257,
    LoadClosure(OpargType<crate::Oparg>) = 258,
    LoadMethod(OpargType<crate::NameIdxOparg>) = 259,
    LoadSuperMethod(OpargType<crate::NameIdxOparg>) = 260,
    LoadZeroSuperAttr(OpargType<crate::NameIdxOparg>) = 261,
    LoadZeroSuperMethod(OpargType<crate::NameIdxOparg>) = 262,
    PopBlock = 263,
    SetupCleanup = 264,
    SetupFinally = 265,
    SetupWith = 266,
    StoreFastMaybeNull(OpargType<crate::Oparg>) = 267,
}

impl PseudoInstruction {
    /// Whether opcode ID have 'HAS_ARG_FLAG' set.
    #[must_use]
    pub const fn has_arg(self) -> bool {
        matches!(
            self,
            Self::Jump(_)
                | Self::JumpNoInterrupt(_)
                | Self::LoadClosure(_)
                | Self::LoadMethod(_)
                | Self::LoadSuperMethod(_)
                | Self::LoadZeroSuperAttr(_)
                | Self::LoadZeroSuperMethod(_)
                | Self::StoreFastMaybeNull(_)
        )
    }

    /// Whether opcode ID have 'HAS_CONST_FLAG' set.
    #[must_use]
    pub const fn has_const(self) -> bool {
        false
    }

    /// Whether opcode ID have 'HAS_PURE_FLAG' set.
    #[must_use]
    pub const fn has_exc(self) -> bool {
        matches!(
            self,
            Self::LoadClosure(_)
                | Self::PopBlock
                | Self::SetupCleanup
                | Self::SetupFinally
                | Self::SetupWith
        )
    }

    /// Whether opcode ID have 'HAS_FREE_FLAG' set.
    #[must_use]
    pub const fn has_free(self) -> bool {
        false
    }

    /// Whether opcode ID have 'HAS_JUMP_FLAG' set.
    #[must_use]
    pub const fn has_jump(self) -> bool {
        matches!(self, Self::Jump(_) | Self::JumpNoInterrupt(_))
    }

    /// Whether opcode ID have 'HAS_LOCAL_FLAG' set.
    #[must_use]
    pub const fn has_local(self) -> bool {
        matches!(self, Self::LoadClosure(_) | Self::StoreFastMaybeNull(_))
    }

    /// Whether opcode ID have 'HAS_NAME_FLAG' set.
    #[must_use]
    pub const fn has_name(self) -> bool {
        matches!(
            self,
            Self::LoadMethod(_)
                | Self::LoadSuperMethod(_)
                | Self::LoadZeroSuperAttr(_)
                | Self::LoadZeroSuperMethod(_)
        )
    }
}

const _: () = assert!(std::mem::size_of::<RealInstruction>() == 1);
const _: () = assert!(std::mem::size_of::<PseudoInstruction>() == 2);
