//! OpargType definitions.

// This file is generated by scripts/generate_oparg_type.py
// Do not edit!

/// Index inside [`CodeObject.constants`](crate::CodeObject.constants).
#[derive(Clone, Copy, Debug)]
pub struct ConstIdx(crate::Oparg);

impl std::ops::Deref for ConstIdx {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used for Instructions like:
///     - [`Instructions::BuildList`]
///     - [`Instructions::UnpackEx`]
#[derive(Clone, Copy, Debug)]
pub struct Count(crate::Oparg);

impl std::ops::Deref for Count {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used for `Jump` instructions.
#[derive(Clone, Copy, Debug)]
pub struct Delta(crate::Oparg);

impl std::ops::Deref for Delta {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Index inside [`CodeObject.names`](crate::CodeObject.names).
#[derive(Clone, Copy, Debug)]
pub struct NameIdx(crate::Oparg);

impl std::ops::Deref for NameIdx {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used by `LoadFast*` [Instruction](crate::Instruction)s.
#[derive(Clone, Copy, Debug)]
pub struct VarNum(crate::Oparg);

impl std::ops::Deref for VarNum {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used for [Instruction::BinOp](crate::Instruction::BinOp).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum BinOp {
    Add = 0,
    And = 1,
    FloorDivide = 2,
    Lshift = 3,
    MatrixMultiply = 4,
    Multiply = 5,
    Remainder = 6,
    Or = 7,
    Power = 8,
    Rshift = 9,
    Subtract = 10,
    TrueDivide = 11,
    Xor = 12,
    InplaceAdd = 13,
    InplaceAnd = 14,
    InplaceFloorDivide = 15,
    InplaceLshift = 16,
    InplaceMatrixMultiply = 17,
    InplaceMultiply = 18,
    InplaceRemainder = 19,
    InplaceOr = 20,
    InplacePower = 21,
    InplaceRshift = 22,
    InplaceSubtract = 23,
    InplaceTrueDivide = 24,
    InplaceXor = 25,
}

/// Used for [Instruction::BuildSlice](crate::Instruction::BuildSlice).
/// Specifies if a slice was built with 2 or 3 arguments.
///
/// For example:
///
/// ```py
/// [0:10] # BuildSlice::Two
/// [0:10:2] # BuildSlice::Three
/// ```
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum BuildSlice {
    Two = 2,
    Three = 3,
}

/// Used for [Instruction::CallIntrinsic1](crate::Instruction::CallIntrinsic1).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum CallIntrinsic1 {
    Print = 0,
    ImportStar = 1,
    StopIterationError = 2,
    AsyncGenWrap = 3,
    UnaryPositive = 4,
    ListToTuple = 5,
    TypeVar = 6,
    ParamSpec = 7,
    TypeVarTuple = 8,
    SubscriptGeneric = 9,
    TypeAlias = 10,
}

/// Used for [Instruction::CallIntrinsic2](crate::Instruction::CallIntrinsic2).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum CallIntrinsic2 {
    Invalid = 0,
    PrepReraiseStar = 1,
    TypeVarWithBound = 2,
    TypeVarWithConstraint = 3,
    SetFunctionTypeParams = 4,
    SetTypeparamDefault = 5,
}

/// Used for [Instruction::Compare](crate::Instruction::Compare).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum Compare {}

/// Used for [Instruction::ConvertValue](crate::Instruction::ConvertValue).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum ConvertValue {
    None = 0x0,
    Str = 0x1,
    Repr = 0x2,
    Ascii = 0x3,
}

/// Used for [Instruction::RaiseVarArgs](crate::Instruction::RaiseVarArgs).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum RaiseVarArgs {
    Reraise = 0,
    Raise = 1,
    RaiseCause = 2,
}

/// Used for [Instruction::RaiseVarArgs](crate::Instruction::RaiseVarArgs).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum RaiseVarArgs {
    Reraise = 0,
    Raise = 1,
    RaiseCause = 2,
}

/// Used for [Instruction::Resume](crate::Instruction::Resume).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum Resume {
    AtFuncStart = 0,
    AfterYield = 1,
    AfterYieldFrom = 2,
    AfterAwait = 3,
}

/// Used for [Instruction::SetFunctionAttribute](crate::Instruction::SetFunctionAttribute).
#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum SetFunctionAttribute {
    Defaults = 0x01,
    KwDefaults = 0x02,
    Annotations = 0x04,
    Closure = 0x08,
}
