//! OpargType definitions.

// This file is generated by scripts/generate_oparg_type.py
// Do not edit!

/// Index inside [`CodeObject.constants`].
///
/// [CodeObject]: [crate::CodeObject]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ConstIdx(crate::Oparg);

impl std::ops::Deref for ConstIdx {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used at instructions like:
/// - [`Instruction::BuildList`]
/// - [`Instruction::UnpackEx`]
///
/// [Instruction]: [crate::Instruction]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Count(crate::Oparg);

impl std::ops::Deref for Count {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used by `Jump*` [`Instruction`]s.
///
/// [Instruction]: [crate::Instruction]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Delta(crate::Oparg);

impl std::ops::Deref for Delta {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Index inside [`CodeObject.names`].
///
/// [CodeObject]: [crate::CodeObject]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct NameIdx(crate::Oparg);

impl std::ops::Deref for NameIdx {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Used by `LoadFast*` [`Instruction`]s.
///
/// [Instruction]: [crate::Instruction]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VarNum(crate::Oparg);

impl std::ops::Deref for VarNum {
    type Target = crate::Oparg;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum BinOp {
    /// `+`
    Add = 0,
    /// `&`
    And = 1,
    /// `//`
    FloorDivide = 2,
    /// `<<`
    Lshift = 3,
    /// `@`
    MatrixMultiply = 4,
    /// `*`
    Multiply = 5,
    /// `%`
    Remainder = 6,
    /// `|`
    Or = 7,
    /// `**`
    Power = 8,
    /// `>>`
    Rshift = 9,
    /// `-`
    Subtract = 10,
    /// `/`
    TrueDivide = 11,
    /// `^`
    Xor = 12,
    /// `+`
    InplaceAdd = 13,
    /// `&=`
    InplaceAnd = 14,
    /// `//=`
    InplaceFloorDivide = 15,
    /// `<<=`
    InplaceLshift = 16,
    /// `@=`
    InplaceMatrixMultiply = 17,
    /// `*=`
    InplaceMultiply = 18,
    /// `%=`
    InplaceRemainder = 19,
    /// `|=`
    InplaceOr = 20,
    /// `**=`
    InplacePower = 21,
    /// `>>=`
    InplaceRshift = 22,
    /// `-=`
    InplaceSubtract = 23,
    /// `/=`
    InplaceTrueDivide = 24,
    /// `^=`
    InplaceXor = 25,
}

/// Specifies if a slice is built with either 2 or 3 arguments.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum BuildSlice {
    /// ```py
    /// x[5:10]
    /// ```
    Two = 2,
    /// ```py
    /// x[5:10:2]`
    /// ```
    Three = 3,
}

/// [`CALL_INTRINSIC_1`]
///
/// [CALL_INTRINSIC_1]: https://docs.python.org/3.13/library/dis.html#opcode-CALL_INTRINSIC_1
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CallIntrinsic1 {
    /// Prints the argument to standard out. Used in the REPL.
    Print = 0,
    /// Performs `import *` for the named module.
    ImportStar = 1,
    /// Extracts the return value from a `StopIteration` exception.
    StopIterationError = 2,
    /// Wraps an async generator value.
    AsyncGenWrap = 3,
    /// Performs the unary `+` operation.
    UnaryPositive = 4,
    /// Converts a list to a tuple.
    ListToTuple = 5,
    /// Creates a [`typing.TypeVar`].
    ///
    /// [typing.TypeVar]: https://docs.python.org/3.13/library/typing.html#typing.TypeVar,
    TypeVar = 6,
    /// Crates a [`typing.ParamSpec`].
    ///
    /// [typing.ParamSpec]: https://docs.python.org/3.13/library/typing.html#typing.ParamSpec
    ParamSpec = 7,
    /// Crates a [`typing.TypeVarTuple`]
    ///
    /// [typing.TypeVarTuple]: https://docs.python.org/3.13/library/typing.html#typing.TypeVarTuple
    TypeVarTuple = 8,
    /// Generic subscript for [`PEP695`].
    ///
    /// [PEP695]: https://peps.python.org/pep-0695/
    SubscriptGeneric = 9,
    /// Creates a [`typing.TypeAliasType`].
    ///
    /// Used in the [`type`] statement. The argument is a tuple of the type aliass name, type parameters, and value.
    ///
    /// [type]: https://docs.python.org/3.13/reference/simple_stmts.html#type
    /// [typing.TypeAliasType]: https://docs.python.org/3.13/library/typing.html#typing.TypeAliasType
    TypeAlias = 10,
}

/// [`CALL_INTRINSIC_2`]
///
/// [CALL_INTRINSIC_2]: https://docs.python.org/3.13/library/dis.html#opcode-CALL_INTRINSIC_2
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CallIntrinsic2 {
    /// Calculates the [`ExceptionGroup`] to raise from a `try-except*`.
    ///
    /// [ExceptionGroup]: https://docs.python.org/3.13/library/exceptions.html#ExceptionGroup
    PrepReraiseStar = 0,
    /// Creates a [`typing.TypeVar`] with a bound.
    ///
    /// [typing.TypeVar]: https://docs.python.org/3.13/library/typing.html#typing.TypeVar
    TypeVarWithBound = 1,
    /// Creates a [`typing.TypeVar`] with constraints.
    ///
    /// [typing.TypeVar]: https://docs.python.org/3.13/library/typing.html#typing.TypeVar
    TypeVarWithConstraint = 2,
    /// Sets the `__type_params__` attribute of a function.
    SetFunctionTypeParams = 3,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ConvertValue {
    /// No conversion.
    None = 0x0,
    /// Converts by calling `str(...)`.
    Str = 0x1,
    /// Converts by calling `repr(...)`.
    Repr = 0x2,
    /// Converts by calling `ascii(...)`.
    Ascii = 0x3,
}

/// When used in the context of:
/// - [`Instruction::IsOp`]:
///     * [`Invert::No`]: Performs `is` comparison.
///     * [`Invert::Yes`]: Performs `is not` comparison.
///
/// - [`Instruction::ContainsOp`]:
///     * [`Invert::No`]: Performs `in` comparison.
///     * [`Invert::Yes`]: Performs `not in` comparison.
///
/// [Instruction]: [crate::Instruction]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Invert {
    No = 0,
    Yes = 1,
}

/// Raises an exception using one of the 3 forms of the `raise` statement.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum RaiseVarArgs {
    /// Re-Raise previous exception.
    ///
    /// ```py
    /// raise
    /// ```
    Reraise = 0,
    /// Raise exception instance or type at `STACK[-1]`.
    ///
    /// ```py
    /// raise STACK[-1]
    /// ```
    Raise = 1,
    /// Raise exception instance or type at `STACK[-2]` with `__cause__` set to `STACK[-1]`.
    ///
    /// ```py
    /// raise STACK[-2] from STACK[-1]
    /// ```
    RaiseCause = 2,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Resume {
    AtFuncStart = 0,
    AfterYield = 1,
    AfterYieldFrom = 2,
    AfterAwait = 3,
}

/// Determines which attribute to set.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SetFunctionAttribute {
    /// A tuple of default values for positional-only and positional-or-keyword parameters in positional order.
    Defaults = 0x01,
    /// A dictionary of keyword-only parameters' default values.
    KwDefaults = 0x02,
    /// A tuple of strings containing parameters' annotations.
    Annotations = 0x04,
    /// A tuple containing cells for free variables, making a closure.
    Closure = 0x08,
}

/// Indicates where the instruction occurs.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Where {
    /// After a call to `__aenter__`.
    AfterAEnter = 0,
    /// After a call to `__aexit__`.
    AfterAExit = 1,
}
