//! OpargType definitions.

// This file is generated by scripts/generate_oparg_type.py
// Do not edit!

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CompareOparg(crate::RawOparg);

/// Index inside [`CodeObject.constants`].
///
/// [CodeObject]: [crate::CodeObject]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ConstIdxOparg(crate::RawOparg);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CountOparg(crate::RawOparg);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DeltaOparg(crate::RawOparg);

/// Index inside [`CodeObject.names`].
///
/// [CodeObject]: [crate::CodeObject]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct NameIdxOparg(crate::RawOparg);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RawOparg(crate::RawOparg);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VarNumOparg(crate::RawOparg);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum BinOpOparg {
    /// `+`
    Add = 0,
    /// `&`
    And = 1,
    /// `//`
    FloorDivide = 2,
    /// `<<`
    Lshift = 3,
    /// `@`
    MatrixMultiply = 4,
    /// `*`
    Multiply = 5,
    /// `%`
    Remainder = 6,
    /// `|`
    Or = 7,
    /// `**`
    Power = 8,
    /// `>>`
    Rshift = 9,
    /// `-`
    Subtract = 10,
    /// `/`
    TrueDivide = 11,
    /// `^`
    Xor = 12,
    /// `+`
    InplaceAdd = 13,
    /// `&=`
    InplaceAnd = 14,
    /// `//=`
    InplaceFloorDivide = 15,
    /// `<<=`
    InplaceLshift = 16,
    /// `@=`
    InplaceMatrixMultiply = 17,
    /// `*=`
    InplaceMultiply = 18,
    /// `%=`
    InplaceRemainder = 19,
    /// `|=`
    InplaceOr = 20,
    /// `**=`
    InplacePower = 21,
    /// `>>=`
    InplaceRshift = 22,
    /// `-=`
    InplaceSubtract = 23,
    /// `/=`
    InplaceTrueDivide = 24,
    /// `^=`
    InplaceXor = 25,
}

/// Specifies if a slice is built with either 2 or 3 arguments.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum BuildSliceOparg {
    /// ```py
    /// x[5:10]
    /// ```
    Two = 2,
    /// ```py
    /// x[5:10:2]
    /// ```
    Three = 3,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CallIntrinsic1Oparg {
    /// Not valid.
    Invalid = 0,
    /// Prints the argument to standard out. Used in the REPL.
    Print = 1,
    /// Performs `import *` for the named module.
    ImportStar = 2,
    /// Extracts the return value from a `StopIteration` exception.
    StopIterationError = 3,
    /// Wraps an async generator value.
    AsyncGenWrap = 4,
    /// Performs the unary `+` operation.
    UnaryPositive = 5,
    /// Converts a list to a tuple.
    ListToTuple = 6,
    /// Creates a [`typing.TypeVar`].
    ///
    /// [typing.TypeVar]: https://docs.python.org/3.13/library/typing.html#typing.TypeVar,
    TypeVar = 7,
    /// Crates a [`typing.ParamSpec`].
    ///
    /// [typing.ParamSpec]: https://docs.python.org/3.13/library/typing.html#typing.ParamSpec
    ParamSpec = 8,
    /// Crates a [`typing.TypeVarTuple`]
    ///
    /// [typing.TypeVarTuple]: https://docs.python.org/3.13/library/typing.html#typing.TypeVarTuple
    TypeVarTuple = 9,
    /// Generic subscript for [`PEP695`].
    ///
    /// [PEP695]: https://peps.python.org/pep-0695/
    SubscriptGeneric = 10,
    /// Creates a [`typing.TypeAliasType`].
    ///
    /// Used in the [`type`] statement. The argument is a tuple of the type aliass name, type parameters, and value.
    ///
    /// [type]: https://docs.python.org/3.13/reference/simple_stmts.html#type
    /// [typing.TypeAliasType]: https://docs.python.org/3.13/library/typing.html#typing.TypeAliasType
    TypeAlias = 11,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CallIntrinsic2Oparg {
    /// Not valid.
    Invalid = 0,
    /// Calculates the [`ExceptionGroup`] to raise from a `try-except*`.
    ///
    /// [ExceptionGroup]: https://docs.python.org/3.13/library/exceptions.html#ExceptionGroup
    PrepReraiseStar = 1,
    /// Creates a [`typing.TypeVar`] with a bound.
    ///
    /// [typing.TypeVar]: https://docs.python.org/3.13/library/typing.html#typing.TypeVar
    TypeVarWithBound = 2,
    /// Creates a [`typing.TypeVar`] with constraints.
    ///
    /// [typing.TypeVar]: https://docs.python.org/3.13/library/typing.html#typing.TypeVar
    TypeVarWithConstraint = 3,
    /// Sets the `__type_params__` attribute of a function.
    SetFunctionTypeParams = 4,
}

/// Used for implementing formatted string literals (f-strings).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ConvertValueOparg {
    /// No conversion.
    None = 0x0,
    /// Converts by calling `str(...)`.
    Str = 0x1,
    /// Converts by calling `repr(...)`.
    Repr = 0x2,
    /// Converts by calling `ascii(...)`.
    Ascii = 0x3,
}

/// When used in the context of:
/// - [`Instruction::IsOp`]:
///     * [`Invert::No`]: Performs `is` comparison.
///     * [`Invert::Yes`]: Performs `is not` comparison.
///
/// - [`Instruction::ContainsOp`]:
///     * [`Invert::No`]: Performs `in` comparison.
///     * [`Invert::Yes`]: Performs `not in` comparison.
///
/// [Instruction]: [crate::Instruction]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum InvertOparg {
    No = 0,
    Yes = 1,
}

/// Raises an exception using one of the 3 forms of the `raise` statement.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum RaiseVarargsOparg {
    /// Re-Raise previous exception.
    ///
    /// ```py
    /// raise
    /// ```
    Reraise = 0,
    /// Raise exception instance or type at `STACK[-1]`.
    ///
    /// ```py
    /// raise STACK[-1]
    /// ```
    Raise = 1,
    /// Raise exception instance or type at `STACK[-2]` with `__cause__` set to `STACK[-1]`.
    ///
    /// ```py
    /// raise STACK[-2] from STACK[-1]
    /// ```
    RaiseCause = 2,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ResumeOparg {
    AtFuncStart = 0,
    AfterYield = 1,
    AfterYieldFrom = 2,
    AfterAwait = 3,
}

/// Determines which attribute to set.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SetFunctionAttributeOparg {
    /// A tuple of default values for positional-only and positional-or-keyword parameters in positional order.
    Defaults = 1,
    /// A dictionary of keyword-only parameters' default values.
    KwDefaults = 2,
    /// A tuple of strings containing parameters' annotations.
    Annotations = 4,
    /// A tuple containing cells for free variables, making a closure.
    Closure = 8,
}

/// Indicates where the instruction occurs.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum WhereOparg {
    /// Nowhere
    NoWhere = 0,
    /// After a call to `__aenter__`.
    AfterAEnter = 1,
    /// After a call to `__aexit__`.
    AfterAExit = 2,
}
