name: Update Actions Caches

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_PROFILE_RELEASE_DEBUG: 0
  CARGO_BUILD_ARGS: "--no-default-features --features threading,stdlib,importlib,stdio,encodings,sqlite,ssl-rustls,host_env"

jobs:
  build-caches:
    name: Build Caches
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            cargo_args: "" # TODO: Fix jit on macos
          - os: ubuntu-latest
            cargo_args: "--features jit"
          - os: windows-latest
            cargo_args: "--features jit"
    steps:
      - name: Get Date
        id: get-date
        run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout RustPython main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # repository: "RustPython/RustPython" # UNCOMMENT BEFORE MERGE
          repository: "ShaharNaveh/RustPython" # DELETE BEFORE MERGE
          ref: main
          persist-credentials: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install RustPython dependencies
        uses: ./.github/actions/install-macos-deps
        with:
          autoconf: true
          automake: true
          libtool: true
          openssl: true

      # Fetch the cache using the complete key - to avoid rebuilding the cache if nothing changed
      - uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}-${{ steps.get-date.outputs.date }}

      # Build RustPython for the dev profile, used by check, doc, ...
      - name: Build dev cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build ${{ env.CARGO_BUILD_ARGS }} ${{ matrix.cargo_args }} --profile dev

      # Build RustPython for the test profile, used by test
      - name: Build test cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build ${{ env.CARGO_BUILD_ARGS }} ${{ matrix.cargo_args }} --profile test

      # Build RustPython for the release profile, used by cpython tests + snippepts
      - name: Build release cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build ${{ env.CARGO_BUILD_ARGS }} ${{ matrix.cargo_args }} --profile release

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}-${{ steps.get-date.outputs.date }}
